<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PlacesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $placesData = [
            // Previous entries (Hotels, Culinary, Shopping, Entertainment)
            [
                'id' => 1,
                'name' => 'Hotel Tentrem Semarang',
                'phonenum' => '+622486005555',
                'email' => 'info.semarang@hoteltentrem.com',
                'location' => 'Jl. Gajahmada No.123, Semarang',
                'desc' => '5-star luxury hotel in downtown Semarang',
                
            ],
            [
                'id' => 2,
                'name' => 'Quest Hotel Semarang',
                'phonenum' => '+62243520808',
                'email' => 'SimpangLimaInfo@Quest-Hotels.com',
                'location' => 'Jl. Plampitan No.37-39, Semarang',
                'desc' => 'Modern business hotel in central location',
                
            ],
            [
                'id' => 3,
                'name' => 'Louis Kienne Pandanaran',
                'phonenum' => '(024) 86453888',
                'email' => 'Info@louisworldwide.com',
                'location' => 'Jl. Pandanaran No.18, Semarang',
                'desc' => 'Serviced apartment style accommodation',
                
            ],
            [
                'id' => 4,
                'name' => 'Mie Ayam Plombokan',
                'phonenum' => '+6288980516870',
                'email' => '',
                'location' => 'Jl. Raya Semarang - Gubug Km. 13, Bandungrejo, Mranggen, Demak Regency',
                'desc' => 'Mie Ayam Plombokan is a typical chicken noodle dish served with chewy noodles, savory shredded chicken, and a rich broth.',
                
            ],
            [
                'id' => 5,
                'name' => 'Tahu Gimbal Pak Edy',
                'phonenum' => '+6281329407509',
                'email' => '',
                'location' => 'Jl. Pandanaran No.2, Mugassari, Semarang',
                'desc' => 'Famous street food with unique peanut sauce',
                
            ],
            [
                'id' => 6,
                'name' => 'Gudeg Koyor Mbak Tum',
                'phonenum' => '+6281222770047',
                'email' => '',
                'location' => 'Jl. MT. Haryono, Wonodri, Semarang',
                'desc' => 'Snug, simple eatery offering a cash-only menu of classic Javanese fare served till late.',
                
            ],
            [
                'id' => 7,
                'name' => 'Lumpia Cik Me Me',
                'phonenum' => '+6285100000727',
                'email' => '',
                'location' => 'Jl. Gajahmada No.107, Miroto',
                'desc' => 'Unpretentious restaurant & shop specializing in rolls filled with crab, vegetables & fish.',
                
            ],
            [
                'id' => 8,
                'name' => 'Bandeng Juwana',
                'phonenum' => '+62811277575',
                'email' => '',
                'location' => 'Jl. Pandanaran No.57, Randusari, Semarang',
                'desc' => 'Premium milkfish dishes and souvenirs',
                
            ],
            [
                'id' => 9,
                'name' => 'Dusun Semilir',
                'phonenum' => '(024) 6789-0123',
                'email' => 'info@dusunsemilir.com',
                'location' => 'Jl. Soekarno-Hatta No.49, Bawen',
                'desc' => 'Eco-friendly tourist attraction with parks, cafes, fun rides, and interesting photo spots at the foot of Mount Ungaran.',
                
            ],
            [
                'id' => 10,
                'name' => 'Saloka Theme Park',
                'phonenum' => '(024) 5432-1098',
                'email' => 'booking@salokathemepark.com',
                'location' => 'Jl. Fatmawati No. 154, Tuntang',
                'desc' => 'Largest amusement park in Central Java, offering exciting rides and attractions for all ages.',
                
            ],
            [
                'id' => 11,
                'name' => 'HW Tiget Club',
                'phonenum' => '(024) 7890-1234',
                'email' => 'reservations@hwtigerclub.com',
                'location' => 'Jl. Cendrawasih No.24, Tj. Mas, Semarang',
                'desc' => 'Famous nightlife venue with an energetic atmosphere, DJ music, and exciting events.',
                
            ],
            [
                'id' => 12,
                'name' => 'Babyface Karaoke',
                'phonenum' => '(024) 2345-6789',
                'email' => 'booking@babyfacekaraoke.com',
                'location' => 'Blok E1/8, Jl. Anjasmoro Raya No.8, Tawangsari, Semarang',
                'desc' => 'Popular karaoke venue offering a wide selection of songs and comfortable rooms.',
                
            ],
            
            // Tourist Attractions
            [
                'id' => 13,
                'name' => 'Lawang Sewu',
                'phonenum' => '(024) 3456-7890',
                'email' => 'info@lawangsewu.com',
                'location' => 'Jl. Pemuda No.160, Semarang',
                'desc' => 'A historic building with rich cultural significance, famous for its architectural beauty and historical importance.',
                
            ],
            [
                'id' => 14,
                'name' => 'Sam Poo Kong Temple',
                'phonenum' => '(024) 5678-9012',
                'email' => 'contact@sampoookong.com',
                'location' => 'Jl. Simongan No.129, Semarang',
                'desc' => 'A historic Chinese temple complex showcasing beautiful traditional architecture and cultural heritage.',
                
            ],
            [
                'id' => 15,
                'name' => 'Old Town (Kota Lama)',
                'phonenum' => '(024) 7890-1234',
                'email' => 'tourism@kotalama.semarang.go.id',
                'location' => 'Jl. Letjen Suprapto No.4, Semarang',
                'desc' => 'A beautiful colonial building in the historic Old Town district, representing Dutch architectural heritage.',
                
            ],
            [
                'id' => 16,
                'name' => 'Tugu Muda Monument',
                'phonenum' => '(024) 2345-6789',
                'email' => 'info@tugumuda.semarang.go.id',
                'location' => 'Simpang Lima, Semarang',
                'desc' => 'An iconic monument symbolizing the spirit of struggle during the Indonesian independence movement.',
                
            ],
            [
                'id' => 17,
                'name' => 'Grand Mosque of Central Java',
                'phonenum' => '(024) 8888-1234',
                'email' => 'info@masjidagung.id',
                'location' => 'Jl. Gajah Raya, Gayamsari, Semarang',
                'desc' => 'Magnificent mosque featuring stunning Islamic architecture and spacious prayer halls.',
            ],
            [
                'id' => 18,
                'name' => 'Wonderia Theme Park',
                'phonenum' => '(024) 7777-5555',
                'email' => 'contact@wonderia.com',
                'location' => 'Jl. Sriwijaya No.29, Semarang',
                'desc' => 'Family-friendly amusement park with various rides and entertainment options.',
            ],
            [
                'id' => 19,
                'name' => 'Brown Canyon',
                'phonenum' => '(024) 3333-9999',
                'email' => 'info@browncanyon.id',
                'location' => 'Rowosari, Tembalang, Semarang',
                'desc' => 'Former quarry turned into a beautiful canyon with stunning views and photo opportunities.',
            ],
            [
                'id' => 20,
                'name' => 'Goa Kreo',
                'phonenum' => '(024) 4444-8888',
                'email' => 'tourism@goakreo.com',
                'location' => 'Kandri, Gunungpati, Semarang',
                'desc' => 'Historic cave with legendary tales and beautiful surrounding reservoir.',
            ],
            [
                'id' => 21,
                'name' => 'Harris Hotel Semarang',
                'phonenum' => '(024) 9999-1111',
                'email' => 'info@harrissemarang.com',
                'location' => 'Jl. Ahmad Yani No.138, Semarang',
                'desc' => 'Modern business hotel with comfortable amenities and strategic location.',
            ],
            [
                'id' => 22,
                'name' => 'Novotel Semarang',
                'phonenum' => '(024) 2222-3333',
                'email' => 'reservation@novotelsemarang.com',
                'location' => 'Jl. Pemuda No.123, Semarang',
                'desc' => 'International standard hotel with excellent facilities and city views.',
            ],
            [
                'id' => 23,
                'name' => 'Waroeng Semawis',
                'phonenum' => '(024) 6666-7777',
                'email' => 'info@waroengsemawis.com',
                'location' => 'Jl. Gang Warung, Semarang',
                'desc' => 'Night market featuring various local delicacies and cultural items.',
            ],
            [
                'id' => 24,
                'name' => 'Semarang Contemporary Art Gallery',
                'phonenum' => '(024) 5555-4444',
                'email' => 'gallery@semarangart.com',
                'location' => 'Jl. Soekarno-Hatta No.55, Semarang',
                'desc' => 'Modern art gallery showcasing local and international contemporary artwork.',
            ],
            [
                'id' => 25,
                'name' => 'Semarang Water Blaster',
                'phonenum' => '(024) 8888-9999',
                'email' => 'fun@waterblaster.com',
                'location' => 'Jl. Marina Raya, Semarang',
                'desc' => 'Water park with exciting slides and pools for family entertainment.',
            ],
            [
                'id' => 26,
                'name' => 'Puri Maerokoco',
                'phonenum' => '(024) 7777-6666',
                'email' => 'info@purimaerokoco.com',
                'location' => 'Jl. Anjasmoro, Semarang',
                'desc' => 'Cultural park featuring miniature traditional houses from Central Java.',
            ],
            [
                'id' => 27,
                'name' => 'Semarang Zoo',
                'phonenum' => '(024) 3333-2222',
                'email' => 'zoo@semarang.go.id',
                'location' => 'Jl. Tegalsari, Semarang',
                'desc' => 'Zoo featuring various animals and educational programs.',
            ],
            [
                'id' => 28,
                'name' => 'Swiss-Belhotel Semarang',
                'phonenum' => '(024) 4444-5555',
                'email' => 'reservations@swiss-belhotelsemarang.com',
                'location' => 'Jl. Abdulrahman Saleh No.1, Semarang',
                'desc' => 'Premium hotel offering luxury accommodations and meeting facilities.',
            ],
            [
                'id' => 29,
                'name' => 'Semawis Food Court',
                'phonenum' => '(024) 6666-8888',
                'email' => 'info@semawisfood.com',
                'location' => 'Jl. Gang Pinggir, Semarang',
                'desc' => 'Popular food court offering various local and international cuisines.',
            ],
            [
                'id' => 30,
                'name' => 'Semarang Night Carnival',
                'phonenum' => '(024) 9999-7777',
                'email' => 'carnival@semarang.com',
                'location' => 'Simpang Lima, Semarang',
                'desc' => 'Evening entertainment venue with rides and games.',
            ],
            [
                'id' => 31,
                'name' => 'Star Hotel Semarang',
                'phonenum' => '(024) 1111-2222',
                'email' => 'info@starhotelsemarang.com',
                'location' => 'Jl. Imam Bonjol No.225, Semarang',
                'desc' => 'Comfortable hotel with modern amenities and business facilities.',
            ],
            [
                'id' => 32,
                'name' => 'Semarang Convention Center',
                'phonenum' => '(024) 2222-4444',
                'email' => 'events@semarangcc.com',
                'location' => 'Jl. Marina No.8, Semarang',
                'desc' => 'Large convention center hosting various events and exhibitions.',
            ],
            [
                'id' => 33,
                'name' => 'Kampung Pelangi',
                'phonenum' => '(024) 5555-6666',
                'email' => 'info@kampungpelangi.id',
                'location' => 'Jl. DR. Sutomo No.89, Semarang',
                'desc' => 'Colorful village known for its rainbow-painted houses and cultural activities.',
            ],
            [
                'id' => 34,
                'name' => 'Museum Ronggowarsito',
                'phonenum' => '(024) 7777-8888',
                'email' => 'museum@ronggowarsito.com',
                'location' => 'Jl. Abdulrahman Saleh No.1, Semarang',
                'desc' => 'Historical museum showcasing Javanese culture and artifacts.',
            ],
            [
                'id' => 35,
                'name' => 'Paragon Mall',
                'phonenum' => '(024) 8888-2222',
                'email' => 'cs@paragonmall.com',
                'location' => 'Jl. Pemuda No.118, Semarang',
                'desc' => 'Modern shopping mall with various retail outlets and entertainment options.',
            ],
            [
                'id' => 36,
                'name' => 'Rasa Semarang Restaurant',
                'phonenum' => '(024) 3333-4444',
                'email' => 'info@rasasemarang.com',
                'location' => 'Jl. Pandanaran No.45, Semarang',
                'desc' => 'Traditional restaurant serving authentic Semarang cuisine.',
            ],
            [
                'id' => 37,
                'name' => 'Gedong Songo Temple',
                'phonenum' => '(024) 6666-5555',
                'email' => 'tourism@gedongsongo.com',
                'location' => 'Candi Gedong Songo, Bandungan',
                'desc' => 'Ancient Hindu temple complex with stunning mountain views.',
            ],
            [
                'id' => 38,
                'name' => 'Marina Beach',
                'phonenum' => '(024) 9999-8888',
                'email' => 'info@marinasemarang.com',
                'location' => 'Jl. Marina, Semarang',
                'desc' => 'Coastal recreation area with various water activities.',
            ],
            [
                'id' => 39,
                'name' => 'ChiCha Tea House',
                'phonenum' => '(024) 1111-3333',
                'email' => 'order@chichatea.com',
                'location' => 'Jl. Gajahmada No.99, Semarang',
                'desc' => 'Modern tea house serving various bubble tea and snacks.',
            ],
            [
                'id' => 40,
                'name' => 'Semarang City Park',
                'phonenum' => '(024) 4444-7777',
                'email' => 'park@semarang.go.id',
                'location' => 'Jl. Menteri Supeno, Semarang',
                'desc' => 'Public park with jogging tracks and recreational facilities.',
            ],
            [
                'id' => 41,
                'name' => 'Cloud Kitchen Hub',
                'phonenum' => '(024) 5555-9999',
                'email' => 'hub@cloudkitchen.com',
                'location' => 'Jl. Majapahit No.123, Semarang',
                'desc' => 'Modern food court featuring various cloud kitchen concepts.',
            ],
            [
                'id' => 42,
                'name' => 'Semarang Heritage Museum',
                'phonenum' => '(024) 7777-1111',
                'email' => 'info@semarangheritage.com',
                'location' => 'Jl. Letjen Suprapto No.9, Semarang',
                'desc' => 'Museum showcasing the history and culture of Semarang.',
            ],
            [
                'id' => 43,
                'name' => 'Sky Dining Restaurant',
                'phonenum' => '(024) 8888-3333',
                'email' => 'reservation@skydining.com',
                'location' => 'Jl. Sisingamangaraja No.15, Semarang',
                'desc' => 'Rooftop restaurant offering panoramic city views.',
            ],
            [
                'id' => 44,
                'name' => 'Green Valley Resort',
                'phonenum' => '(024) 2222-5555',
                'email' => 'booking@greenvalley.com',
                'location' => 'Jl. Ungaran Barat, Semarang',
                'desc' => 'Mountain resort with outdoor activities and cool climate.',
            ],
            [
                'id' => 45,
                'name' => 'Art Deco Market',
                'phonenum' => '(024) 6666-9999',
                'email' => 'market@artdeco.com',
                'location' => 'Jl. Agus Salim, Semarang',
                'desc' => 'Traditional market in an art deco building selling local products.',
            ],
            [
                'id' => 46,
                'name' => 'Digital Innovation Hub',
                'phonenum' => '(024) 9999-4444',
                'email' => 'hub@digitalinnovation.com',
                'location' => 'Jl. Pahlawan No.10, Semarang',
                'desc' => 'Modern workspace and technology innovation center.',
            ],
            [
                'id' => 47,
                'name' => 'Sport Center Semarang',
                'phonenum' => '(024) 3333-7777',
                'email' => 'info@sportcenter.com',
                'location' => 'Jl. Veteran No.77, Semarang',
                'desc' => 'Comprehensive sports facility with various athletic programs.',
            ],
            [
                'id' => 48,
                'name' => 'Culinary Street Market',
                'phonenum' => '(024) 4444-1111',
                'email' => 'market@culinary.com',
                'location' => 'Jl. MT Haryono, Semarang',
                'desc' => 'Street food market featuring local delicacies.',
            ],
            [
                'id' => 49,
                'name' => 'Eco Park Semarang',
                'phonenum' => '(024) 5555-2222',
                'email' => 'info@ecopark.com',
                'location' => 'Jl. Kedungmundu Raya, Semarang',
                'desc' => 'Ecological park with educational programs and green spaces.',
            ],
            [
                'id' => 50,
                'name' => 'Heritage Coffee House',
                'phonenum' => '(024) 7777-3333',
                'email' => 'coffee@heritage.com',
                'location' => 'Jl. Pemuda No.56, Semarang',
                'desc' => 'Vintage coffee shop in a restored colonial building.',
            ],
            [
                'id' => 51,
                'name' => 'Flower Garden Park',
                'phonenum' => '(024) 1111-4444',
                'email' => 'garden@flowerpark.com',
                'location' => 'Jl. Tlogosari Raya, Semarang',
                'desc' => 'Beautiful botanical garden featuring various flower species.',
            ],
            [
                'id' => 52,
                'name' => 'Urban Gaming Center',
                'phonenum' => '(024) 2222-6666',
                'email' => 'play@urbangaming.com',
                'location' => 'Jl. Setiabudi No.88, Semarang',
                'desc' => 'Modern gaming center with latest console and PC games.',
            ],
            [
                'id' => 53,
                'name' => 'Javanese Culture Center',
                'phonenum' => '(024) 3333-8888',
                'email' => 'info@javaculture.com',
                'location' => 'Jl. Diponegoro No.45, Semarang',
                'desc' => 'Cultural center showcasing traditional Javanese arts.',
            ],
            [
                'id' => 54,
                'name' => 'Hill View Restaurant',
                'phonenum' => '(024) 4444-2222',
                'email' => 'dine@hillview.com',
                'location' => 'Jl. Gombel Raya, Semarang',
                'desc' => 'Restaurant with panoramic city views and local cuisine.',
            ],
            [
                'id' => 55,
                'name' => 'Tech Innovation Mall',
                'phonenum' => '(024) 5555-3333',
                'email' => 'info@techmall.com',
                'location' => 'Jl. Majapahit No.234, Semarang',
                'desc' => 'Shopping center focusing on technology and gadgets.',
            ],
            [
                'id' => 56,
                'name' => 'Harmony Spa & Wellness',
                'phonenum' => '(024) 6666-1111',
                'email' => 'booking@harmonyspa.com',
                'location' => 'Jl. Pandanaran No.89, Semarang',
                'desc' => 'Luxury spa offering traditional and modern treatments.',
            ],
            [
                'id' => 57,
                'name' => 'Street Art Gallery',
                'phonenum' => '(024) 7777-4444',
                'email' => 'art@streetgallery.com',
                'location' => 'Jl. Pemuda No.167, Semarang',
                'desc' => 'Urban art gallery featuring local street artists.',
            ],
            [
                'id' => 58,
                'name' => 'Central Market Square',
                'phonenum' => '(024) 8888-5555',
                'email' => 'market@central.com',
                'location' => 'Jl. MT Haryono No.345, Semarang',
                'desc' => 'Modern marketplace with local and international products.',
            ],
            [
                'id' => 59,
                'name' => 'Adventure Park Semarang',
                'phonenum' => '(024) 9999-6666',
                'email' => 'info@adventurepark.com',
                'location' => 'Jl. Ungaran Timur, Semarang',
                'desc' => 'Outdoor adventure park with various activities.',
            ],
            [
                'id' => 60,
                'name' => 'Historic Train Station',
                'phonenum' => '(024) 1111-7777',
                'email' => 'info@historictrain.com',
                'location' => 'Jl. Tawang No.1, Semarang',
                'desc' => 'Preserved colonial-era train station with museum.',
            ],
            [
                'id' => 61,
                'name' => 'Floating Market Semarang',
                'phonenum' => '(024) 2222-8888',
                'email' => 'market@floating.com',
                'location' => 'Jl. Marina Raya No.56, Semarang',
                'desc' => 'Traditional market on boats selling local products.',
            ],
            [
                'id' => 62,
                'name' => 'Bamboo Eco Resort',
                'phonenum' => '(024) 3333-9999',
                'email' => 'stay@bambooresort.com',
                'location' => 'Jl. Ungaran Selatan, Semarang',
                'desc' => 'Eco-friendly resort built with sustainable materials.',
            ],
            [
                'id' => 63,
                'name' => 'Digital Art Museum',
                'phonenum' => '(024) 4444-3333',
                'email' => 'museum@digitalart.com',
                'location' => 'Jl. Pahlawan No.234, Semarang',
                'desc' => 'Interactive museum featuring digital art installations.',
            ],
            [
                'id' => 64,
                'name' => 'Sunset Beach Club',
                'phonenum' => '(024) 5555-4444',
                'email' => 'club@sunsetbeach.com',
                'location' => 'Jl. Marina Beach, Semarang',
                'desc' => 'Beachfront club with live music and events.',
            ],
            [
                'id' => 65,
                'name' => 'Traditional Puppet Theater',
                'phonenum' => '(024) 6666-2222',
                'email' => 'theater@puppet.com',
                'location' => 'Jl. Pemuda No.89, Semarang',
                'desc' => 'Theater showcasing traditional wayang performances.',
            ],
            [
                'id' => 66,
                'name' => 'Sky Bridge Park',
                'phonenum' => '(024) 7777-5555',
                'email' => 'info@skybridge.com',
                'location' => 'Jl. Sisingamangaraja No.45, Semarang',
                'desc' => 'Elevated park with walking trails and city views.',
            ],
            [
                'id' => 67,
                'name' => 'Modern Art Center',
                'phonenum' => '(024) 8888-6666',
                'email' => 'art@moderncenter.com',
                'location' => 'Jl. Pandanaran No.123, Semarang',
                'desc' => 'Contemporary art center with rotating exhibitions.',
            ],
            [
                'id' => 68,
                'name' => 'Local Food Market',
                'phonenum' => '(024) 9999-7777',
                'email' => 'market@localfood.com',
                'location' => 'Jl. MT Haryono No.567, Semarang',
                'desc' => 'Market specializing in local Semarang delicacies.',
            ],
            [
                'id' => 69,
                'name' => 'Science Discovery Center',
                'phonenum' => '(024) 1111-8888',
                'email' => 'discover@science.com',
                'location' => 'Jl. Veteran No.234, Semarang',
                'desc' => 'Interactive science museum with educational exhibits.',
            ],
            [
                'id' => 70,
                'name' => 'Heritage Walking Trail',
                'phonenum' => '(024) 2222-9999',
                'email' => 'trail@heritage.com',
                'location' => 'Kota Lama, Semarang',
                'desc' => 'Guided walking trail through historic district.',
            ],
            [
                'id' => 71,
                'name' => 'Urban Farming Center',
                'phonenum' => '(024) 3333-1111',
                'email' => 'farm@urban.com',
                'location' => 'Jl. Kedungmundu No.78, Semarang',
                'desc' => 'Educational center for urban agriculture.',
            ],
            [
                'id' => 72,
                'name' => 'Crystal Convention Hall',
                'phonenum' => '(024) 4444-5555',
                'email' => 'events@crystal.com',
                'location' => 'Jl. Ahmad Yani No.345, Semarang',
                'desc' => 'Modern convention center for various events.',
            ],
            [
                'id' => 73,
                'name' => 'Historical Photo Gallery',
                'phonenum' => '(024) 5555-6666',
                'email' => 'gallery@historical.com',
                'location' => 'Jl. Letjen Suprapto No.67, Semarang',
                'desc' => 'Gallery showcasing historical photographs of Semarang.',
            ],
            [
                'id' => 74,
                'name' => 'Riverside Food Court',
                'phonenum' => '(024) 6666-7777',
                'email' => 'food@riverside.com',
                'location' => 'Jl. Mpu Tantular No.12, Semarang',
                'desc' => 'Food court with river view and various cuisines.',
            ],
            [
                'id' => 75,
                'name' => 'Virtual Reality Center',
                'phonenum' => '(024) 7777-8888',
                'email' => 'vr@center.com',
                'location' => 'Jl. Setiabudi No.123, Semarang',
                'desc' => 'Entertainment center featuring VR experiences.',
            ],
            [
                'id' => 76,
                'name' => 'Batik Workshop Center',
                'phonenum' => '(024) 8888-9999',
                'email' => 'workshop@batik.com',
                'location' => 'Jl. Gajahmada No.234, Semarang',
                'desc' => 'Cultural center offering batik making workshops.',
            ],
            [
                'id' => 77,
                'name' => 'Mountain View Hotel',
                'phonenum' => '(024) 9999-1111',
                'email' => 'stay@mountainview.com',
                'location' => 'Jl. Ungaran Indah No.45, Semarang',
                'desc' => 'Hotel with panoramic mountain views and spa.',
            ],
            [
                'id' => 78,
                'name' => 'Indoor Sports Complex',
                'phonenum' => '(024) 1111-2222',
                'email' => 'sports@indoor.com',
                'location' => 'Jl. Majapahit No.456, Semarang',
                'desc' => 'Modern indoor sports facility with various courts.',
            ],
            [
                'id' => 79,
                'name' => 'Herbal Medicine Market',
                'phonenum' => '(024) 2222-3333',
                'email' => 'market@herbal.com',
                'location' => 'Jl. Veteran No.89, Semarang',
                'desc' => 'Traditional market selling herbal medicines.',
            ],
            [
                'id' => 80,
                'name' => 'Lake View Park',
                'phonenum' => '(024) 3333-4444',
                'email' => 'park@lakeview.com',
                'location' => 'Jl. Rawa Pening No.12, Semarang',
                'desc' => 'Recreational park around a beautiful lake.',
            ],
            [
                'id' => 81,
                'name' => 'Creative Hub Semarang',
                'phonenum' => '(024) 4444-5555',
                'email' => 'hub@creative.com',
                'location' => 'Jl. Pemuda No.345, Semarang',
                'desc' => 'Coworking space for creative industries.',
            ],
            [
                'id' => 82,
                'name' => 'Traditional Dance Studio',
                'phonenum' => '(024) 5555-6666',
                'email' => 'dance@traditional.com',
                'location' => 'Jl. Diponegoro No.78, Semarang',
                'desc' => 'Studio teaching traditional Javanese dances.',
            ],
            [
                'id' => 83,
                'name' => 'Culinary Innovation Lab',
                'phonenum' => '(024) 6666-7777',
                'email' => 'lab@culinary.com',
                'location' => 'Jl. MT Haryono No.890, Semarang',
                'desc' => 'Experimental kitchen for culinary innovation.',
            ],
            [
                'id' => 84,
                'name' => 'Wellness Center Spa',
                'phonenum' => '(024) 7777-8888',
                'email' => 'spa@wellness.com',
                'location' => 'Jl. Pandanaran No.234, Semarang',
                'desc' => 'Comprehensive wellness and spa center.',
            ],
            [
                'id' => 85,
                'name' => 'Music Studio Complex',
                'phonenum' => '(024) 8888-9999',
                'email' => 'studio@music.com',
                'location' => 'Jl. Gajahmada No.567, Semarang',
                'desc' => 'Professional music recording studios.',
            ],
            [
                'id' => 86,
                'name' => 'Educational Science Park',
                'phonenum' => '(024) 9999-1111',
                'email' => 'park@science.com',
                'location' => 'Jl. Setiabudi No.89, Semarang',
                'desc' => 'Outdoor science learning center for students.',
            ],
            [
                'id' => 87,
                'name' => 'Heritage Boutique Hotel',
                'phonenum' => '(024) 1111-2222',
                'email' => 'stay@heritageboutique.com',
                'location' => 'Jl. Letjen Suprapto No.45, Semarang',
                'desc' => 'Boutique hotel in restored colonial building.',
            ],
            [
                'id' => 88,
                'name' => 'Modern Library Complex',
                'phonenum' => '(024) 2222-3333',
                'email' => 'library@modern.com',
                'location' => 'Jl. Pahlawan No.123, Semarang',
                'desc' => 'Contemporary library with digital resources.',
            ],
            [
                'id' => 89,
                'name' => 'Youth Activity Center',
                'phonenum' => '(024) 3333-4444',
                'email' => 'youth@activity.com',
                'location' => 'Jl. Veteran No.456, Semarang',
                'desc' => 'Recreation center for youth activities.',
            ],
            [
                'id' => 90,
                'name' => 'Pet Park and Cafe',
                'phonenum' => '(024) 4444-5555',
                'email' => 'cafe@petpark.com',
                'location' => 'Jl. Sisingamangaraja No.78, Semarang',
                'desc' => 'Pet-friendly park with cafe facilities.',
            ],
            [
                'id' => 91,
                'name' => 'Local Craft Market',
                'phonenum' => '(024) 5555-6666',
                'email' => 'market@localcraft.com',
                'location' => 'Jl. MT Haryono No.234, Semarang',
                'desc' => 'Market showcasing local handicrafts.',
            ],
            [
                'id' => 92,
                'name' => 'Skating Rink Arena',
                'phonenum' => '(024) 6666-7777',
                'email' => 'arena@skating.com',
                'location' => 'Jl. Majapahit No.567, Semarang',
                'desc' => 'Indoor skating rink for all ages.',
            ],
            [
                'id' => 93,
                'name' => 'Pottery Workshop',
                'phonenum' => '(024) 7777-8888',
                'email' => 'workshop@pottery.com',
                'location' => 'Jl. Diponegoro No.890, Semarang',
                'desc' => 'Traditional pottery making workshop.',
            ],
            [
                'id' => 94,
                'name' => 'Business Convention Center',
                'phonenum' => '(024) 8888-9999',
                'email' => 'center@business.com',
                'location' => 'Jl. Ahmad Yani No.123, Semarang',
                'desc' => 'Modern facility for business events.',
            ],
            [
                'id' => 95,
                'name' => 'Cultural Fashion House',
                'phonenum' => '(024) 9999-1111',
                'email' => 'fashion@cultural.com',
                'location' => 'Jl. Pemuda No.456, Semarang',
                'desc' => 'Fashion center featuring traditional designs.',
            ],
            [
                'id' => 96,
                'name' => 'Aquatic Research Center',
                'phonenum' => '(024) 1111-2222',
                'email' => 'research@aquatic.com',
                'location' => 'Jl. Marina No.78, Semarang',
                'desc' => 'Marine research and education facility.',
            ],
            [
                'id' => 97,
                'name' => 'Urban Forest Park',
                'phonenum' => '(024) 2222-3333',
                'email' => 'park@urbanforest.com',
                'location' => 'Jl. Kedungmundu No.234, Semarang',
                'desc' => 'Green space with native tree species.',
            ],
            [
                'id' => 98,
                'name' => 'Film Studio Complex',
                'phonenum' => '(024) 3333-4444',
                'email' => 'studio@film.com',
                'location' => 'Jl. Siliwangi No.567, Semarang',
                'desc' => 'Professional film production facility.',
            ],
            [
                'id' => 99,
                'name' => 'Innovation Learning Center',
                'phonenum' => '(024) 4444-5555',
                'email' => 'learn@innovation.com',
                'location' => 'Jl. Veteran No.890, Semarang',
                'desc' => 'Educational center for technology innovation.',
            ],
            [
                'id' => 100,
                'name' => 'Heritage Art Gallery',
                'phonenum' => '(024) 5555-6666',
                'email' => 'gallery@heritageart.com',
                'location' => 'Jl. Letjen Suprapto No.123, Semarang',
                'desc' => 'Art gallery in historic building featuring local artists.',
            ]

        ];

        DB::table('places')->insert($placesData);
    }
}