<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PlacesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $placesData = [
            // Previous entries (Hotels, Culinary, Shopping, Entertainment)
            [
                'name' => 'Hotel Tentrem Semarang',
                'phonenum' => '+622486005555',
                'email' => 'info.semarang@hoteltentrem.com',
                'location' => 'Jl. Gajahmada No.123, Semarang',
                'desc' => '5-star luxury hotel in downtown Semarang',
                
            ],
            [
                'name' => 'Quest Hotel Semarang',
                'phonenum' => '+62243520808',
                'email' => 'SimpangLimaInfo@Quest-Hotels.com',
                'location' => 'Jl. Plampitan No.37-39, Semarang',
                'desc' => 'Modern business hotel in central location',
                
            ],
            [
                'name' => 'Louis Kienne Pandanaran',
                'phonenum' => '(024) 86453888',
                'email' => 'Info@louisworldwide.com',
                'location' => 'Jl. Pandanaran No.18, Semarang',
                'desc' => 'Serviced apartment style accommodation',
                
            ],
            [
                'name' => 'Mie Ayam Plombokan',
                'phonenum' => '+6288980516870',
                'email' => '',
                'location' => 'Jl. Raya Semarang - Gubug Km. 13, Bandungrejo, Mranggen, Demak Regency',
                'desc' => 'Mie Ayam Plombokan is a typical chicken noodle dish served with chewy noodles, savory shredded chicken, and a rich broth.',
                
            ],
            [
                'name' => 'Tahu Gimbal Pak Edy',
                'phonenum' => '+6281329407509',
                'email' => '',
                'location' => 'Jl. Pandanaran No.2, Mugassari, Semarang',
                'desc' => 'Famous street food with unique peanut sauce',
                
            ],
            [
                'name' => 'Gudeg Koyor Mbak Tum',
                'phonenum' => '+6281222770047',
                'email' => '',
                'location' => 'Jl. MT. Haryono, Wonodri, Semarang',
                'desc' => 'Snug, simple eatery offering a cash-only menu of classic Javanese fare served till late.',
                
            ],
            [
                'name' => 'Lumpia Cik Me Me',
                'phonenum' => '+6285100000727',
                'email' => '',
                'location' => 'Jl. Gajahmada No.107, Miroto',
                'desc' => 'Unpretentious restaurant & shop specializing in rolls filled with crab, vegetables & fish.',
                
            ],
            [
                'name' => 'Bandeng Juwana',
                'phonenum' => '+62811277575',
                'email' => '',
                'location' => 'Jl. Pandanaran No.57, Randusari, Semarang',
                'desc' => 'Premium milkfish dishes and souvenirs',
                
            ],
            [
                'name' => 'Dusun Semilir',
                'phonenum' => '(024) 6789-0123',
                'email' => 'info@dusunsemilir.com',
                'location' => 'Jl. Soekarno-Hatta No.49, Bawen',
                'desc' => 'Eco-friendly tourist attraction with parks, cafes, fun rides, and interesting photo spots at the foot of Mount Ungaran.',
                
            ],
            [
                'name' => 'Saloka Theme Park',
                'phonenum' => '(024) 5432-1098',
                'email' => 'booking@salokathemepark.com',
                'location' => 'Jl. Fatmawati No. 154, Tuntang',
                'desc' => 'Largest amusement park in Central Java, offering exciting rides and attractions for all ages.',
                
            ],
            [
                'name' => 'HW Tiget Club',
                'phonenum' => '(024) 7890-1234',
                'email' => 'reservations@hwtigerclub.com',
                'location' => 'Jl. Cendrawasih No.24, Tj. Mas, Semarang',
                'desc' => 'Famous nightlife venue with an energetic atmosphere, DJ music, and exciting events.',
                
            ],
            [
                'name' => 'Babyface Karaoke',
                'phonenum' => '(024) 2345-6789',
                'email' => 'booking@babyfacekaraoke.com',
                'location' => 'Blok E1/8, Jl. Anjasmoro Raya No.8, Tawangsari, Semarang',
                'desc' => 'Popular karaoke venue offering a wide selection of songs and comfortable rooms.',
                
            ],
            
            // Tourist Attractions
            [
                'name' => 'Lawang Sewu',
                'phonenum' => '(024) 3456-7890',
                'email' => 'info@lawangsewu.com',
                'location' => 'Jl. Pemuda No.160, Semarang',
                'desc' => 'A historic building with rich cultural significance, famous for its architectural beauty and historical importance.',
                
            ],
            [
                'name' => 'Sam Poo Kong Temple',
                'phonenum' => '(024) 5678-9012',
                'email' => 'contact@sampoookong.com',
                'location' => 'Jl. Simongan No.129, Semarang',
                'desc' => 'A historic Chinese temple complex showcasing beautiful traditional architecture and cultural heritage.',
                
            ],
            [
                'name' => 'Old Town (Kota Lama)',
                'phonenum' => '(024) 7890-1234',
                'email' => 'tourism@kotalama.semarang.go.id',
                'location' => 'Jl. Letjen Suprapto No.4, Semarang',
                'desc' => 'A beautiful colonial building in the historic Old Town district, representing Dutch architectural heritage.',
                
            ],
            [
                'name' => 'Tugu Muda Monument',
                'phonenum' => '(024) 2345-6789',
                'email' => 'info@tugumuda.semarang.go.id',
                'location' => 'Simpang Lima, Semarang',
                'desc' => 'An iconic monument symbolizing the spirit of struggle during the Indonesian independence movement.',
                
            ],
            [
                'name' => 'Grand Mosque of Central Java',
                'phonenum' => '(024) 8888-1234',
                'email' => 'info@masjidagung.id',
                'location' => 'Jl. Gajah Raya, Gayamsari, Semarang',
                'desc' => 'Magnificent mosque featuring stunning Islamic architecture and spacious prayer halls.',
            ],
            [
                'name' => 'Wonderia Theme Park',
                'phonenum' => '(024) 7777-5555',
                'email' => 'contact@wonderia.com',
                'location' => 'Jl. Sriwijaya No.29, Semarang',
                'desc' => 'Family-friendly amusement park with various rides and entertainment options.',
            ],
            [
                'name' => 'Brown Canyon',
                'phonenum' => '(024) 3333-9999',
                'email' => 'info@browncanyon.id',
                'location' => 'Rowosari, Tembalang, Semarang',
                'desc' => 'Former quarry turned into a beautiful canyon with stunning views and photo opportunities.',
            ],
            [
                'name' => 'Goa Kreo',
                'phonenum' => '(024) 4444-8888',
                'email' => 'tourism@goakreo.com',
                'location' => 'Kandri, Gunungpati, Semarang',
                'desc' => 'Historic cave with legendary tales and beautiful surrounding reservoir.',
            ],
            [
                'name' => 'Harris Hotel Semarang',
                'phonenum' => '(024) 9999-1111',
                'email' => 'info@harrissemarang.com',
                'location' => 'Jl. Ahmad Yani No.138, Semarang',
                'desc' => 'Modern business hotel with comfortable amenities and strategic location.',
            ],
            [
                'name' => 'Novotel Semarang',
                'phonenum' => '(024) 2222-3333',
                'email' => 'reservation@novotelsemarang.com',
                'location' => 'Jl. Pemuda No.123, Semarang',
                'desc' => 'International standard hotel with excellent facilities and city views.',
            ],
            [
                'name' => 'Waroeng Semawis',
                'phonenum' => '(024) 6666-7777',
                'email' => 'info@waroengsemawis.com',
                'location' => 'Jl. Gang Warung, Semarang',
                'desc' => 'Night market featuring various local delicacies and cultural items.',
            ],
            [
                'name' => 'Semarang Contemporary Art Gallery',
                'phonenum' => '(024) 5555-4444',
                'email' => 'gallery@semarangart.com',
                'location' => 'Jl. Soekarno-Hatta No.55, Semarang',
                'desc' => 'Modern art gallery showcasing local and international contemporary artwork.',
            ],
            [
                'name' => 'Semarang Water Blaster',
                'phonenum' => '(024) 8888-9999',
                'email' => 'fun@waterblaster.com',
                'location' => 'Jl. Marina Raya, Semarang',
                'desc' => 'Water park with exciting slides and pools for family entertainment.',
            ],
            [
                'name' => 'Puri Maerokoco',
                'phonenum' => '(024) 7777-6666',
                'email' => 'info@purimaerokoco.com',
                'location' => 'Jl. Anjasmoro, Semarang',
                'desc' => 'Cultural park featuring miniature traditional houses from Central Java.',
            ],
            [
                'name' => 'Semarang Zoo',
                'phonenum' => '(024) 3333-2222',
                'email' => 'zoo@semarang.go.id',
                'location' => 'Jl. Tegalsari, Semarang',
                'desc' => 'Zoo featuring various animals and educational programs.',
            ],
            [
                'name' => 'Swiss-Belhotel Semarang',
                'phonenum' => '(024) 4444-5555',
                'email' => 'reservations@swiss-belhotelsemarang.com',
                'location' => 'Jl. Abdulrahman Saleh No.1, Semarang',
                'desc' => 'Premium hotel offering luxury accommodations and meeting facilities.',
            ],
            [
                'name' => 'Semawis Food Court',
                'phonenum' => '(024) 6666-8888',
                'email' => 'info@semawisfood.com',
                'location' => 'Jl. Gang Pinggir, Semarang',
                'desc' => 'Popular food court offering various local and international cuisines.',
            ],
            [
                'name' => 'Semarang Night Carnival',
                'phonenum' => '(024) 9999-7777',
                'email' => 'carnival@semarang.com',
                'location' => 'Simpang Lima, Semarang',
                'desc' => 'Evening entertainment venue with rides and games.',
            ],
            [
                'name' => 'Star Hotel Semarang',
                'phonenum' => '(024) 1111-2222',
                'email' => 'info@starhotelsemarang.com',
                'location' => 'Jl. Imam Bonjol No.225, Semarang',
                'desc' => 'Comfortable hotel with modern amenities and business facilities.',
            ],
            [
                'name' => 'Semarang Convention Center',
                'phonenum' => '(024) 2222-4444',
                'email' => 'events@semarangcc.com',
                'location' => 'Jl. Marina No.8, Semarang',
                'desc' => 'Large convention center hosting various events and exhibitions.',
            ],
            [
                'name' => 'Kampung Pelangi',
                'phonenum' => '(024) 5555-6666',
                'email' => 'info@kampungpelangi.id',
                'location' => 'Jl. DR. Sutomo No.89, Semarang',
                'desc' => 'Colorful village known for its rainbow-painted houses and cultural activities.',
            ],
            [
                'name' => 'Museum Ronggowarsito',
                'phonenum' => '(024) 7777-8888',
                'email' => 'museum@ronggowarsito.com',
                'location' => 'Jl. Abdulrahman Saleh No.1, Semarang',
                'desc' => 'Historical museum showcasing Javanese culture and artifacts.',
            ],
            [
                'name' => 'Paragon Mall',
                'phonenum' => '(024) 8888-2222',
                'email' => 'cs@paragonmall.com',
                'location' => 'Jl. Pemuda No.118, Semarang',
                'desc' => 'Modern shopping mall with various retail outlets and entertainment options.',
            ],
            [
                'name' => 'Rasa Semarang Restaurant',
                'phonenum' => '(024) 3333-4444',
                'email' => 'info@rasasemarang.com',
                'location' => 'Jl. Pandanaran No.45, Semarang',
                'desc' => 'Traditional restaurant serving authentic Semarang cuisine.',
            ],
            [
                'name' => 'Gedong Songo Temple',
                'phonenum' => '(024) 6666-5555',
                'email' => 'tourism@gedongsongo.com',
                'location' => 'Candi Gedong Songo, Bandungan',
                'desc' => 'Ancient Hindu temple complex with stunning mountain views.',
            ],
            [
                'name' => 'Marina Beach',
                'phonenum' => '(024) 9999-8888',
                'email' => 'info@marinasemarang.com',
                'location' => 'Jl. Marina, Semarang',
                'desc' => 'Coastal recreation area with various water activities.',
            ],
            [
                'name' => 'ChiCha Tea House',
                'phonenum' => '(024) 1111-3333',
                'email' => 'order@chichatea.com',
                'location' => 'Jl. Gajahmada No.99, Semarang',
                'desc' => 'Modern tea house serving various bubble tea and snacks.',
            ],
            [
                'name' => 'Semarang City Park',
                'phonenum' => '(024) 4444-7777',
                'email' => 'park@semarang.go.id',
                'location' => 'Jl. Menteri Supeno, Semarang',
                'desc' => 'Public park with jogging tracks and recreational facilities.',
            ],
            [
                'name' => 'Cloud Kitchen Hub',
                'phonenum' => '(024) 5555-9999',
                'email' => 'hub@cloudkitchen.com',
                'location' => 'Jl. Majapahit No.123, Semarang',
                'desc' => 'Modern food court featuring various cloud kitchen concepts.',
            ],
            [
                'name' => 'Semarang Heritage Museum',
                'phonenum' => '(024) 7777-1111',
                'email' => 'info@semarangheritage.com',
                'location' => 'Jl. Letjen Suprapto No.9, Semarang',
                'desc' => 'Museum showcasing the history and culture of Semarang.',
            ],
            [
                'name' => 'Sky Dining Restaurant',
                'phonenum' => '(024) 8888-3333',
                'email' => 'reservation@skydining.com',
                'location' => 'Jl. Sisingamangaraja No.15, Semarang',
                'desc' => 'Rooftop restaurant offering panoramic city views.',
            ],
            [
                'name' => 'Green Valley Resort',
                'phonenum' => '(024) 2222-5555',
                'email' => 'booking@greenvalley.com',
                'location' => 'Jl. Ungaran Barat, Semarang',
                'desc' => 'Mountain resort with outdoor activities and cool climate.',
            ],
            [
                'name' => 'Art Deco Market',
                'phonenum' => '(024) 6666-9999',
                'email' => 'market@artdeco.com',
                'location' => 'Jl. Agus Salim, Semarang',
                'desc' => 'Traditional market in an art deco building selling local products.',
            ],
            [
                'name' => 'Digital Innovation Hub',
                'phonenum' => '(024) 9999-4444',
                'email' => 'hub@digitalinnovation.com',
                'location' => 'Jl. Pahlawan No.10, Semarang',
                'desc' => 'Modern workspace and technology innovation center.',
            ],
            [
                'name' => 'Sport Center Semarang',
                'phonenum' => '(024) 3333-7777',
                'email' => 'info@sportcenter.com',
                'location' => 'Jl. Veteran No.77, Semarang',
                'desc' => 'Comprehensive sports facility with various athletic programs.',
            ],
            [
                'name' => 'Culinary Street Market',
                'phonenum' => '(024) 4444-1111',
                'email' => 'market@culinary.com',
                'location' => 'Jl. MT Haryono, Semarang',
                'desc' => 'Street food market featuring local delicacies.',
            ],
            [
                'name' => 'Eco Park Semarang',
                'phonenum' => '(024) 5555-2222',
                'email' => 'info@ecopark.com',
                'location' => 'Jl. Kedungmundu Raya, Semarang',
                'desc' => 'Ecological park with educational programs and green spaces.',
            ],
            [
                'name' => 'Heritage Coffee House',
                'phonenum' => '(024) 7777-3333',
                'email' => 'coffee@heritage.com',
                'location' => 'Jl. Pemuda No.56, Semarang',
                'desc' => 'Vintage coffee shop in a restored colonial building.',
            ],
            [
                'name' => 'Flower Garden Park',
                'phonenum' => '(024) 1111-4444',
                'email' => 'garden@flowerpark.com',
                'location' => 'Jl. Tlogosari Raya, Semarang',
                'desc' => 'Beautiful botanical garden featuring various flower species.',
            ],
            [
                'name' => 'Urban Gaming Center',
                'phonenum' => '(024) 2222-6666',
                'email' => 'play@urbangaming.com',
                'location' => 'Jl. Setiabudi No.88, Semarang',
                'desc' => 'Modern gaming center with latest console and PC games.',
            ],
            [
                'name' => 'Javanese Culture Center',
                'phonenum' => '(024) 3333-8888',
                'email' => 'info@javaculture.com',
                'location' => 'Jl. Diponegoro No.45, Semarang',
                'desc' => 'Cultural center showcasing traditional Javanese arts.',
            ],
            [
                'name' => 'Hill View Restaurant',
                'phonenum' => '(024) 4444-2222',
                'email' => 'dine@hillview.com',
                'location' => 'Jl. Gombel Raya, Semarang',
                'desc' => 'Restaurant with panoramic city views and local cuisine.',
            ],
            [
                'name' => 'Tech Innovation Mall',
                'phonenum' => '(024) 5555-3333',
                'email' => 'info@techmall.com',
                'location' => 'Jl. Majapahit No.234, Semarang',
                'desc' => 'Shopping center focusing on technology and gadgets.',
            ],
            [
                'name' => 'Harmony Spa & Wellness',
                'phonenum' => '(024) 6666-1111',
                'email' => 'booking@harmonyspa.com',
                'location' => 'Jl. Pandanaran No.89, Semarang',
                'desc' => 'Luxury spa offering traditional and modern treatments.',
            ],
            [
                'name' => 'Street Art Gallery',
                'phonenum' => '(024) 7777-4444',
                'email' => 'art@streetgallery.com',
                'location' => 'Jl. Pemuda No.167, Semarang',
                'desc' => 'Urban art gallery featuring local street artists.',
            ],
            [
                'name' => 'Central Market Square',
                'phonenum' => '(024) 8888-5555',
                'email' => 'market@central.com',
                'location' => 'Jl. MT Haryono No.345, Semarang',
                'desc' => 'Modern marketplace with local and international products.',
            ],
            [
                'name' => 'Adventure Park Semarang',
                'phonenum' => '(024) 9999-6666',
                'email' => 'info@adventurepark.com',
                'location' => 'Jl. Ungaran Timur, Semarang',
                'desc' => 'Outdoor adventure park with various activities.',
            ],
            [
                'name' => 'Historic Train Station',
                'phonenum' => '(024) 1111-7777',
                'email' => 'info@historictrain.com',
                'location' => 'Jl. Tawang No.1, Semarang',
                'desc' => 'Preserved colonial-era train station with museum.',
            ],
            [
                'name' => 'Floating Market Semarang',
                'phonenum' => '(024) 2222-8888',
                'email' => 'market@floating.com',
                'location' => 'Jl. Marina Raya No.56, Semarang',
                'desc' => 'Traditional market on boats selling local products.',
            ],
            [
                'name' => 'Bamboo Eco Resort',
                'phonenum' => '(024) 3333-9999',
                'email' => 'stay@bambooresort.com',
                'location' => 'Jl. Ungaran Selatan, Semarang',
                'desc' => 'Eco-friendly resort built with sustainable materials.',
            ],
            [
                'name' => 'Digital Art Museum',
                'phonenum' => '(024) 4444-3333',
                'email' => 'museum@digitalart.com',
                'location' => 'Jl. Pahlawan No.234, Semarang',
                'desc' => 'Interactive museum featuring digital art installations.',
            ],
            [
                'name' => 'Sunset Beach Club',
                'phonenum' => '(024) 5555-4444',
                'email' => 'club@sunsetbeach.com',
                'location' => 'Jl. Marina Beach, Semarang',
                'desc' => 'Beachfront club with live music and events.',
            ],
            [
                'name' => 'Traditional Puppet Theater',
                'phonenum' => '(024) 6666-2222',
                'email' => 'theater@puppet.com',
                'location' => 'Jl. Pemuda No.89, Semarang',
                'desc' => 'Theater showcasing traditional wayang performances.',
            ],
            [
                'name' => 'Sky Bridge Park',
                'phonenum' => '(024) 7777-5555',
                'email' => 'info@skybridge.com',
                'location' => 'Jl. Sisingamangaraja No.45, Semarang',
                'desc' => 'Elevated park with walking trails and city views.',
            ],
            [
                'name' => 'Modern Art Center',
                'phonenum' => '(024) 8888-6666',
                'email' => 'art@moderncenter.com',
                'location' => 'Jl. Pandanaran No.123, Semarang',
                'desc' => 'Contemporary art center with rotating exhibitions.',
            ],
            [
                'name' => 'Local Food Market',
                'phonenum' => '(024) 9999-7777',
                'email' => 'market@localfood.com',
                'location' => 'Jl. MT Haryono No.567, Semarang',
                'desc' => 'Market specializing in local Semarang delicacies.',
            ],
            [
                'name' => 'Science Discovery Center',
                'phonenum' => '(024) 1111-8888',
                'email' => 'discover@science.com',
                'location' => 'Jl. Veteran No.234, Semarang',
                'desc' => 'Interactive science museum with educational exhibits.',
            ],
            [
                'name' => 'Heritage Walking Trail',
                'phonenum' => '(024) 2222-9999',
                'email' => 'trail@heritage.com',
                'location' => 'Kota Lama, Semarang',
                'desc' => 'Guided walking trail through historic district.',
            ],
            [
                'name' => 'Urban Farming Center',
                'phonenum' => '(024) 3333-1111',
                'email' => 'farm@urban.com',
                'location' => 'Jl. Kedungmundu No.78, Semarang',
                'desc' => 'Educational center for urban agriculture.',
            ],
            [
                'name' => 'Crystal Convention Hall',
                'phonenum' => '(024) 4444-5555',
                'email' => 'events@crystal.com',
                'location' => 'Jl. Ahmad Yani No.345, Semarang',
                'desc' => 'Modern convention center for various events.',
            ],
            [
                'name' => 'Historical Photo Gallery',
                'phonenum' => '(024) 5555-6666',
                'email' => 'gallery@historical.com',
                'location' => 'Jl. Letjen Suprapto No.67, Semarang',
                'desc' => 'Gallery showcasing historical photographs of Semarang.',
            ],
            [
                'name' => 'Riverside Food Court',
                'phonenum' => '(024) 6666-7777',
                'email' => 'food@riverside.com',
                'location' => 'Jl. Mpu Tantular No.12, Semarang',
                'desc' => 'Food court with river view and various cuisines.',
            ],
            [
                'name' => 'Virtual Reality Center',
                'phonenum' => '(024) 7777-8888',
                'email' => 'vr@center.com',
                'location' => 'Jl. Setiabudi No.123, Semarang',
                'desc' => 'Entertainment center featuring VR experiences.',
            ],
            [
                'name' => 'Batik Workshop Center',
                'phonenum' => '(024) 8888-9999',
                'email' => 'workshop@batik.com',
                'location' => 'Jl. Gajahmada No.234, Semarang',
                'desc' => 'Cultural center offering batik making workshops.',
            ],
            [
                'name' => 'Mountain View Hotel',
                'phonenum' => '(024) 9999-1111',
                'email' => 'stay@mountainview.com',
                'location' => 'Jl. Ungaran Indah No.45, Semarang',
                'desc' => 'Hotel with panoramic mountain views and spa.',
            ],
            [
                'name' => 'Indoor Sports Complex',
                'phonenum' => '(024) 1111-2222',
                'email' => 'sports@indoor.com',
                'location' => 'Jl. Majapahit No.456, Semarang',
                'desc' => 'Modern indoor sports facility with various courts.',
            ],
            [
                'name' => 'Herbal Medicine Market',
                'phonenum' => '(024) 2222-3333',
                'email' => 'market@herbal.com',
                'location' => 'Jl. Veteran No.89, Semarang',
                'desc' => 'Traditional market selling herbal medicines.',
            ],
            [
                'name' => 'Lake View Park',
                'phonenum' => '(024) 3333-4444',
                'email' => 'park@lakeview.com',
                'location' => 'Jl. Rawa Pening No.12, Semarang',
                'desc' => 'Recreational park around a beautiful lake.',
            ],
            [
                'name' => 'Creative Hub Semarang',
                'phonenum' => '(024) 4444-5555',
                'email' => 'hub@creative.com',
                'location' => 'Jl. Pemuda No.345, Semarang',
                'desc' => 'Coworking space for creative industries.',
            ],
            [
                'name' => 'Traditional Dance Studio',
                'phonenum' => '(024) 5555-6666',
                'email' => 'dance@traditional.com',
                'location' => 'Jl. Diponegoro No.78, Semarang',
                'desc' => 'Studio teaching traditional Javanese dances.',
            ],
            [
                'name' => 'Culinary Innovation Lab',
                'phonenum' => '(024) 6666-7777',
                'email' => 'lab@culinary.com',
                'location' => 'Jl. MT Haryono No.890, Semarang',
                'desc' => 'Experimental kitchen for culinary innovation.',
            ],
            [
                'name' => 'Wellness Center Spa',
                'phonenum' => '(024) 7777-8888',
                'email' => 'spa@wellness.com',
                'location' => 'Jl. Pandanaran No.234, Semarang',
                'desc' => 'Comprehensive wellness and spa center.',
            ],
            [
                'name' => 'Music Studio Complex',
                'phonenum' => '(024) 8888-9999',
                'email' => 'studio@music.com',
                'location' => 'Jl. Gajahmada No.567, Semarang',
                'desc' => 'Professional music recording studios.',
            ],
            [
                'name' => 'Educational Science Park',
                'phonenum' => '(024) 9999-1111',
                'email' => 'park@science.com',
                'location' => 'Jl. Setiabudi No.89, Semarang',
                'desc' => 'Outdoor science learning center for students.',
            ],
            [
                'name' => 'Heritage Boutique Hotel',
                'phonenum' => '(024) 1111-2222',
                'email' => 'stay@heritageboutique.com',
                'location' => 'Jl. Letjen Suprapto No.45, Semarang',
                'desc' => 'Boutique hotel in restored colonial building.',
            ],
            [
                'name' => 'Modern Library Complex',
                'phonenum' => '(024) 2222-3333',
                'email' => 'library@modern.com',
                'location' => 'Jl. Pahlawan No.123, Semarang',
                'desc' => 'Contemporary library with digital resources.',
            ],
            [
                'name' => 'Youth Activity Center',
                'phonenum' => '(024) 3333-4444',
                'email' => 'youth@activity.com',
                'location' => 'Jl. Veteran No.456, Semarang',
                'desc' => 'Recreation center for youth activities.',
            ],
            [
                'name' => 'Pet Park and Cafe',
                'phonenum' => '(024) 4444-5555',
                'email' => 'cafe@petpark.com',
                'location' => 'Jl. Sisingamangaraja No.78, Semarang',
                'desc' => 'Pet-friendly park with cafe facilities.',
            ],
            [
                'name' => 'Local Craft Market',
                'phonenum' => '(024) 5555-6666',
                'email' => 'market@localcraft.com',
                'location' => 'Jl. MT Haryono No.234, Semarang',
                'desc' => 'Market showcasing local handicrafts.',
            ],
            [
                'name' => 'Skating Rink Arena',
                'phonenum' => '(024) 6666-7777',
                'email' => 'arena@skating.com',
                'location' => 'Jl. Majapahit No.567, Semarang',
                'desc' => 'Indoor skating rink for all ages.',
            ],
            [
                'name' => 'Pottery Workshop',
                'phonenum' => '(024) 7777-8888',
                'email' => 'workshop@pottery.com',
                'location' => 'Jl. Diponegoro No.890, Semarang',
                'desc' => 'Traditional pottery making workshop.',
            ],
            [
                'name' => 'Business Convention Center',
                'phonenum' => '(024) 8888-9999',
                'email' => 'center@business.com',
                'location' => 'Jl. Ahmad Yani No.123, Semarang',
                'desc' => 'Modern facility for business events.',
            ],
            [
                'name' => 'Cultural Fashion House',
                'phonenum' => '(024) 9999-1111',
                'email' => 'fashion@cultural.com',
                'location' => 'Jl. Pemuda No.456, Semarang',
                'desc' => 'Fashion center featuring traditional designs.',
            ],
            [
                'name' => 'Aquatic Research Center',
                'phonenum' => '(024) 1111-2222',
                'email' => 'research@aquatic.com',
                'location' => 'Jl. Marina No.78, Semarang',
                'desc' => 'Marine research and education facility.',
            ],
            [
                'name' => 'Urban Forest Park',
                'phonenum' => '(024) 2222-3333',
                'email' => 'park@urbanforest.com',
                'location' => 'Jl. Kedungmundu No.234, Semarang',
                'desc' => 'Green space with native tree species.',
            ],
            [
                'name' => 'Film Studio Complex',
                'phonenum' => '(024) 3333-4444',
                'email' => 'studio@film.com',
                'location' => 'Jl. Siliwangi No.567, Semarang',
                'desc' => 'Professional film production facility.',
            ],
            [
                'name' => 'Innovation Learning Center',
                'phonenum' => '(024) 4444-5555',
                'email' => 'learn@innovation.com',
                'location' => 'Jl. Veteran No.890, Semarang',
                'desc' => 'Educational center for technology innovation.',
            ],
            [
                'name' => 'Heritage Art Gallery',
                'phonenum' => '(024) 5555-6666',
                'email' => 'gallery@heritageart.com',
                'location' => 'Jl. Letjen Suprapto No.123, Semarang',
                'desc' => 'Art gallery in historic building featuring local artists.',
            ],
            [
                'name' => 'Dusun Semilir Entertainment',
                'phonenum' => '(024) 6789-1201',
                'email' => 'info@dusunsemilir2.com',
                'location' => 'Jl. Soekarno-Hatta No.149, Bawen',
                'desc' => 'Modern entertainment complex featuring various attractions and activities.',
            ],
            [
                'name' => 'Saloka Park Plus',
                'phonenum' => '(024) 5432-1202',
                'email' => 'info@salokaplus.com',
                'location' => 'Jl. Fatmawati No.254, Tuntang',
                'desc' => 'Extended theme park area with additional rides and entertainment zones.',
            ],
            [
                'name' => 'HW Entertainment Hub',
                'phonenum' => '(024) 7890-1203',
                'email' => 'info@hwentertainment.com',
                'location' => 'Jl. Cendrawasih No.124, Semarang',
                'desc' => 'Modern entertainment complex with multiple venues and activities.',
            ],
            [
                'name' => 'Babyface Premium',
                'phonenum' => '(024) 2345-1204',
                'email' => 'premium@babyface.com',
                'location' => 'Jl. Anjasmoro Raya No.18, Semarang',
                'desc' => 'Upscale karaoke venue with premium facilities.',
            ],
            [
                'name' => 'Water Blaster Extreme',
                'phonenum' => '(024) 8888-1205',
                'email' => 'extreme@waterblaster.com',
                'location' => 'Jl. Marina Raya No.50, Semarang',
                'desc' => 'Advanced water park with extreme slides and attractions.',
            ],
            [
                'name' => 'NAV Karaoke Club',
                'phonenum' => '(024) 3333-1206',
                'email' => 'club@navkaraoke.com',
                'location' => 'Jl. Pandanaran No.106, Semarang',
                'desc' => 'Modern karaoke club with premium sound systems.',
            ],
            [
                'name' => 'Happy Puppy VIP',
                'phonenum' => '(024) 7777-1207',
                'email' => 'vip@happypuppy.com',
                'location' => 'Jl. Gajah Mada No.107, Semarang',
                'desc' => 'VIP karaoke rooms with high-end amenities.',
            ],
            [
                'name' => 'XXI Premiere',
                'phonenum' => '(024) 9999-1208',
                'email' => 'premiere@xxi.com',
                'location' => 'Jl. Pemuda No.108, Semarang',
                'desc' => 'Premium cinema experience with luxury seating.',
            ],
            [
                'name' => 'CGV Gold Class',
                'phonenum' => '(024) 8888-1209',
                'email' => 'gold@cgv.com',
                'location' => 'Jl. Ahmad Yani No.109, Semarang',
                'desc' => 'Luxury cinema with exclusive amenities.',
            ],
            [
                'name' => 'Semarang Entertainment Center',
                'phonenum' => '(024) 7777-1210',
                'email' => 'info@semargentertainment.com',
                'location' => 'Jl. Pahlawan No.110, Semarang',
                'desc' => 'Multi-purpose entertainment venue.',
            ],
            [
                'name' => 'Wonder Park Plus',
                'phonenum' => '(024) 6666-1211',
                'email' => 'plus@wonderpark.com',
                'location' => 'Jl. Majapahit No.111, Semarang',
                'desc' => 'Family entertainment park with various attractions.',
            ],
            [
                'name' => 'Club M2 Premium',
                'phonenum' => '(024) 5555-1212',
                'email' => 'premium@clubm2.com',
                'location' => 'Jl. Gajah Mada No.112, Semarang',
                'desc' => 'Upscale nightclub with premium services.',
            ],
            [
                'name' => 'E-Plaza Gaming',
                'phonenum' => '(024) 4444-1213',
                'email' => 'gaming@eplaza.com',
                'location' => 'Jl. Pandanaran No.113, Semarang',
                'desc' => 'Modern gaming center with latest equipment.',
            ],
            [
                'name' => 'Avatar Club Elite',
                'phonenum' => '(024) 3333-1214',
                'email' => 'elite@avatarclub.com',
                'location' => 'Jl. Pemuda No.114, Semarang',
                'desc' => 'Premium entertainment club with VIP areas.',
            ],
            [
                'name' => 'The Room Gaming Pro',
                'phonenum' => '(024) 2222-1215',
                'email' => 'pro@roomgaming.com',
                'location' => 'Jl. Siliwangi No.115, Semarang',
                'desc' => 'Professional gaming center with tournament facilities.',
            ],
            [
                'name' => 'Timezone Premium',
                'phonenum' => '(024) 1111-1216',
                'email' => 'premium@timezone.com',
                'location' => 'Jl. Pahlawan No.116, Semarang',
                'desc' => 'Advanced arcade gaming center.',
            ],
            [
                'name' => 'Amazon Sports Center',
                'phonenum' => '(024) 9999-1217',
                'email' => 'sports@amazon.com',
                'location' => 'Jl. Veteran No.117, Semarang',
                'desc' => 'Modern sports and recreation facility.',
            ],
            [
                'name' => 'Olympic Bowling Center',
                'phonenum' => '(024) 8888-1218',
                'email' => 'bowling@olympic.com',
                'location' => 'Jl. MT Haryono No.118, Semarang',
                'desc' => 'Professional bowling center with modern lanes.',
            ],
            [
                'name' => 'Victory Sports Club',
                'phonenum' => '(024) 7777-1219',
                'email' => 'club@victorysports.com',
                'location' => 'Jl. Diponegoro No.119, Semarang',
                'desc' => 'Multi-sport facility with modern equipment.',
            ],
            [
                'name' => '3D Art World',
                'phonenum' => '(024) 6666-1220',
                'email' => 'art@3dworld.com',
                'location' => 'Jl. Gajahmada No.120, Semarang',
                'desc' => 'Interactive 3D art museum and gallery.',
            ],
            [
                'name' => 'Wonder Park Plus',
                'phonenum' => '(024) 6666-1211',
                'email' => 'plus@wonderpark.com',
                'location' => 'Jl. Majapahit No.111, Semarang',
                'desc' => 'Family entertainment park with various attractions.',
            ],
            [
                'name' => 'Club M2 Premium',
                'phonenum' => '(024) 5555-1212',
                'email' => 'premium@clubm2.com',
                'location' => 'Jl. Gajah Mada No.112, Semarang',
                'desc' => 'Upscale nightclub with premium services.',
            ],
            [
                'name' => 'E-Plaza Gaming',
                'phonenum' => '(024) 4444-1213',
                'email' => 'gaming@eplaza.com',
                'location' => 'Jl. Pandanaran No.113, Semarang',
                'desc' => 'Modern gaming center with latest equipment.',
            ],
            [
                'name' => 'Avatar Club Elite',
                'phonenum' => '(024) 3333-1214',
                'email' => 'elite@avatarclub.com',
                'location' => 'Jl. Pemuda No.114, Semarang',
                'desc' => 'Premium entertainment club with VIP areas.',
            ],
            [
                'name' => 'The Room Gaming Pro',
                'phonenum' => '(024) 2222-1215',
                'email' => 'pro@roomgaming.com',
                'location' => 'Jl. Siliwangi No.115, Semarang',
                'desc' => 'Professional gaming center with tournament facilities.',
            ],
            [
                'name' => 'Timezone Premium',
                'phonenum' => '(024) 1111-1216',
                'email' => 'premium@timezone.com',
                'location' => 'Jl. Pahlawan No.116, Semarang',
                'desc' => 'Advanced arcade gaming center.',
            ],
            [
                'name' => 'Amazon Sports Center',
                'phonenum' => '(024) 9999-1217',
                'email' => 'sports@amazon.com',
                'location' => 'Jl. Veteran No.117, Semarang',
                'desc' => 'Modern sports and recreation facility.',
            ],
            [
                'name' => 'Olympic Bowling Center',
                'phonenum' => '(024) 8888-1218',
                'email' => 'bowling@olympic.com',
                'location' => 'Jl. MT Haryono No.118, Semarang',
                'desc' => 'Professional bowling center with modern lanes.',
            ],
            [
                'name' => 'Victory Sports Club',
                'phonenum' => '(024) 7777-1219',
                'email' => 'club@victorysports.com',
                'location' => 'Jl. Diponegoro No.119, Semarang',
                'desc' => 'Multi-sport facility with modern equipment.',
            ],
            [
                'name' => '3D Art World',
                'phonenum' => '(024) 6666-1220',
                'email' => 'art@3dworld.com',
                'location' => 'Jl. Gajahmada No.120, Semarang',
                'desc' => 'Interactive 3D art museum and gallery.',
            ],
            [
                'name' => 'Wonder Park Plus',
                'phonenum' => '(024) 6666-1211',
                'email' => 'plus@wonderpark.com',
                'location' => 'Jl. Majapahit No.111, Semarang',
                'desc' => 'Family entertainment park with various attractions.',
            ],
            [
                'name' => 'Club M2 Premium',
                'phonenum' => '(024) 5555-1212',
                'email' => 'premium@clubm2.com',
                'location' => 'Jl. Gajah Mada No.112, Semarang',
                'desc' => 'Upscale nightclub with premium services.',
            ],
            [
                'name' => 'E-Plaza Gaming',
                'phonenum' => '(024) 4444-1213',
                'email' => 'gaming@eplaza.com',
                'location' => 'Jl. Pandanaran No.113, Semarang',
                'desc' => 'Modern gaming center with latest equipment.',
            ],
            [
                'name' => 'Avatar Club Elite',
                'phonenum' => '(024) 3333-1214',
                'email' => 'elite@avatarclub.com',
                'location' => 'Jl. Pemuda No.114, Semarang',
                'desc' => 'Premium entertainment club with VIP areas.',
            ],
            [
                'name' => 'The Room Gaming Pro',
                'phonenum' => '(024) 2222-1215',
                'email' => 'pro@roomgaming.com',
                'location' => 'Jl. Siliwangi No.115, Semarang',
                'desc' => 'Professional gaming center with tournament facilities.',
            ],
            [
                'name' => 'Timezone Premium',
                'phonenum' => '(024) 1111-1216',
                'email' => 'premium@timezone.com',
                'location' => 'Jl. Pahlawan No.116, Semarang',
                'desc' => 'Advanced arcade gaming center.',
            ],
            [
                'name' => 'Amazon Sports Center',
                'phonenum' => '(024) 9999-1217',
                'email' => 'sports@amazon.com',
                'location' => 'Jl. Veteran No.117, Semarang',
                'desc' => 'Modern sports and recreation facility.',
            ],
            [
                'name' => 'Olympic Bowling Center',
                'phonenum' => '(024) 8888-1218',
                'email' => 'bowling@olympic.com',
                'location' => 'Jl. MT Haryono No.118, Semarang',
                'desc' => 'Professional bowling center with modern lanes.',
            ],
            [
                'name' => 'Victory Sports Club',
                'phonenum' => '(024) 7777-1219',
                'email' => 'club@victorysports.com',
                'location' => 'Jl. Diponegoro No.119, Semarang',
                'desc' => 'Multi-sport facility with modern equipment.',
            ],
            [
                'name' => '3D Art World',
                'phonenum' => '(024) 6666-1220',
                'email' => 'art@3dworld.com',
                'location' => 'Jl. Gajahmada No.120, Semarang',
                'desc' => 'Interactive 3D art museum and gallery.',
            ],
            [
                'name' => 'Contemporary Arts Space',
                'phonenum' => '(024) 5555-1221',
                'email' => 'info@contemporaryarts.com',
                'location' => 'Jl. Pemuda No.121, Semarang',
                'desc' => 'Modern art gallery with interactive exhibitions.',
            ],
            [
                'name' => 'Old City 3D Museum Plus',
                'phonenum' => '(024) 4444-1222',
                'email' => 'plus@oldcity3d.com',
                'location' => 'Jl. Letjen Suprapto No.122, Semarang',
                'desc' => 'Enhanced 3D museum with historical themes.',
            ],
            [
                'name' => 'D\'Project Dance Hub',
                'phonenum' => '(024) 3333-1223',
                'email' => 'hub@dproject.com',
                'location' => 'Jl. Pandanaran No.123, Semarang',
                'desc' => 'Modern dance studio with multiple practice rooms.',
            ],
            [
                'name' => 'Arena VR Plus',
                'phonenum' => '(024) 2222-1224',
                'email' => 'plus@arenavr.com',
                'location' => 'Jl. Gajah Mada No.124, Semarang',
                'desc' => 'Advanced virtual reality gaming center.',
            ],
            [
                'name' => 'MovieBox Premium',
                'phonenum' => '(024) 1111-1225',
                'email' => 'premium@moviebox.com',
                'location' => 'Jl. Ahmad Yani No.125, Semarang',
                'desc' => 'Luxury cinema with premium facilities.',
            ],
            [
                'name' => 'Inul Vista Gold',
                'phonenum' => '(024) 9999-1226',
                'email' => 'gold@inulvista.com',
                'location' => 'Jl. Majapahit No.126, Semarang',
                'desc' => 'Premium karaoke venue with VIP rooms.',
            ],
            [
                'name' => 'Jatidiri Sports Complex',
                'phonenum' => '(024) 8888-1227',
                'email' => 'complex@jatidiri.com',
                'location' => 'Jl. Veteran No.127, Semarang',
                'desc' => 'Comprehensive sports facility with modern equipment.',
            ],
            [
                'name' => 'Q-Time Family Center',
                'phonenum' => '(024) 7777-1228',
                'email' => 'family@qtime.com',
                'location' => 'Jl. MT Haryono No.128, Semarang',
                'desc' => 'Family entertainment center with various activities.',
            ],
            [
                'name' => 'Galaxy Sports Club',
                'phonenum' => '(024) 6666-1229',
                'email' => 'club@galaxysports.com',
                'location' => 'Jl. Siliwangi No.129, Semarang',
                'desc' => 'Modern sports club with diverse facilities.',
            ],
            [
                'name' => 'Night Market Central',
                'phonenum' => '(024) 5555-1230',
                'email' => 'central@nightmarket.com',
                'location' => 'Jl. Pahlawan No.130, Semarang',
                'desc' => 'Vibrant night market with entertainment options.',
            ],
            [
                'name' => 'Fun World Entertainment',
                'phonenum' => '(024) 4444-1231',
                'email' => 'fun@funworld.com',
                'location' => 'Jl. Pemuda No.131, Semarang',
                'desc' => 'Family entertainment center with arcade games.',
             ],
             [
                'name' => 'Game Master Pro',
                'phonenum' => '(024) 3333-1232', 
                'email' => 'pro@gamemaster.com',
                'location' => 'Jl. Pandanaran No.132, Semarang',
                'desc' => 'Professional gaming center with latest consoles.',
             ],
             [
                'name' => 'Energy Entertainment Zone',
                'phonenum' => '(024) 2222-1233',
                'email' => 'zone@energy.com',
                'location' => 'Jl. Gajah Mada No.133, Semarang',
                'desc' => 'Multi-zone entertainment complex.',
             ],
             [
                'name' => 'Laga Bola Center',
                'phonenum' => '(024) 1111-1234',
                'email' => 'center@lagabola.com',
                'location' => 'Jl. Ahmad Yani No.134, Semarang',
                'desc' => 'Indoor soccer and sports facility.',
             ],
             [
                'name' => 'THR Family Park',
                'phonenum' => '(024) 9999-1235',
                'email' => 'family@thr.com',
                'location' => 'Jl. Majapahit No.135, Semarang',
                'desc' => 'Traditional entertainment park for families.',
             ],
             [
                'name' => 'Studio 27 Music Center',
                'phonenum' => '(024) 8888-1236',
                'email' => 'music@studio27.com',
                'location' => 'Jl. Veteran No.136, Semarang',
                'desc' => 'Professional music recording and practice facility.',
             ],
             [
                'name' => 'Bounce Street Zone',
                'phonenum' => '(024) 7777-1237',
                'email' => 'zone@bouncestreet.com',
                'location' => 'Jl. MT Haryono No.137, Semarang',
                'desc' => 'Trampoline park with various activities.',
             ],
             [
                'name' => 'Kids Castle Playground',
                'phonenum' => '(024) 6666-1238',
                'email' => 'play@kidscastle.com',
                'location' => 'Jl. Siliwangi No.138, Semarang',
                'desc' => 'Indoor playground for children.',
             ],
             [
                'name' => 'Grand Photo Studio',
                'phonenum' => '(024) 5555-1239',
                'email' => 'studio@grandphoto.com',
                'location' => 'Jl. Pahlawan No.139, Semarang',
                'desc' => 'Professional photo studio with various sets.',
             ],
             [
                'name' => 'Extreme Adventure Park',
                'phonenum' => '(024) 4444-1240',
                'email' => 'adventure@extreme.com',
                'location' => 'Jl. Pemuda No.140, Semarang',
                'desc' => 'Outdoor adventure park with extreme activities.',
             ],
             [
                'name' => 'Art Performance Hall',
                'phonenum' => '(024) 3333-1241',
                'email' => 'hall@artperformance.com',
                'location' => 'Jl. Pandanaran No.141, Semarang',
                'desc' => 'Venue for art performances and exhibitions.',
             ],
             [
                'name' => 'Digital Park Innovation',
                'phonenum' => '(024) 2222-1242',
                'email' => 'innovation@digitalpark.com',
                'location' => 'Jl. Gajah Mada No.142, Semarang',
                'desc' => 'Interactive digital entertainment center.',
             ],
             [
                'name' => 'Adventure Zone Plus',
                'phonenum' => '(024) 1111-1243',
                'email' => 'plus@adventurezone.com',
                'location' => 'Jl. Ahmad Yani No.143, Semarang',
                'desc' => 'Indoor adventure park with various challenges.',
             ],
             [
                'name' => 'Ice Skating World',
                'phonenum' => '(024) 9999-1244',
                'email' => 'world@iceskating.com',
                'location' => 'Jl. Majapahit No.144, Semarang',
                'desc' => 'Indoor ice skating rink with training programs.',
             ],
             [
                'name' => 'Royal Cinema Plus',
                'phonenum' => '(024) 8888-1245',
                'email' => 'plus@royalcinema.com',
                'location' => 'Jl. Veteran No.145, Semarang',
                'desc' => 'Premium cinema with luxury services.',
             ],
             [
                'name' => 'Ultimate Gaming Arena',
                'phonenum' => '(024) 7777-1246',
                'email' => 'arena@ultimategaming.com',
                'location' => 'Jl. MT Haryono No.146, Semarang',
                'desc' => 'Comprehensive gaming facility with tournaments.',
             ],
             [
                'name' => 'Sky Adventure World',
                'phonenum' => '(024) 6666-1247',
                'email' => 'world@skyadventure.com',
                'location' => 'Jl. Siliwangi No.147, Semarang',
                'desc' => 'Elevated adventure park with various activities.',
             ],
             [
                'name' => 'Racing Kart Pro',
                'phonenum' => '(024) 5555-1248',
                'email' => 'pro@racingkart.com',
                'location' => 'Jl. Pahlawan No.148, Semarang',
                'desc' => 'Professional go-kart racing facility.',
             ],
             [
                'name' => 'Live Music Center',
                'phonenum' => '(024) 4444-1249',
                'email' => 'center@livemusic.com',
                'location' => 'Jl. Pemuda No.149, Semarang',
                'desc' => 'Venue for live music performances.',
             ],
             [
                'name' => 'Fantasy World Park',
                'phonenum' => '(024) 3333-1250',
                'email' => 'park@fantasyworld.com',
                'location' => 'Jl. Pandanaran No.150, Semarang',
                'desc' => 'Themed entertainment park for all ages.',
             ],
             [
                'name' => 'Lawang Sewu Heritage',
                'phonenum' => '(024) 2222-1251',
                'email' => 'heritage@lawangsewu.com',
                'location' => 'Jl. Pemuda No.151, Semarang',
                'desc' => 'Historic Dutch colonial building with museum.',
            ],
            [
                'name' => 'Sam Poo Kong Complex',
                'phonenum' => '(024) 3333-1252',
                'email' => 'complex@sammpookong.com',
                'location' => 'Jl. Simongan No.152, Semarang',
                'desc' => 'Historic Chinese temple complex with cultural exhibits.',
            ],
            [
                'name' => 'Kota Lama Heritage',
                'phonenum' => '(024) 4444-1253',
                'email' => 'heritage@kotalama.com',
                'location' => 'Jl. Letjen Suprapto No.153, Semarang',
                'desc' => 'Historic district with Dutch colonial architecture.',
            ],
            [
                'name' => 'Tugu Muda Complex',
                'phonenum' => '(024) 5555-1254',
                'email' => 'complex@tugumuda.com',
                'location' => 'Jl. Pandanaran No.154, Semarang',
                'desc' => 'Historic monument and surrounding gardens.',
            ],
            [
                'name' => 'Masjid Agung Complex',
                'phonenum' => '(024) 6666-1255',
                'email' => 'complex@masjidagung.com',
                'location' => 'Jl. Gajah Raya No.155, Semarang',
                'desc' => 'Grand mosque with Islamic architecture.',
            ],
            [
                'name' => 'Brown Canyon Park',
                'phonenum' => '(024) 7777-1256',
                'email' => 'park@browncanyon.com',
                'location' => 'Jl. Rowosari No.156, Semarang',
                'desc' => 'Natural canyon with hiking trails.',
            ],
            [
                'name' => 'Goa Kreo Cave',
                'phonenum' => '(024) 8888-1257',
                'email' => 'cave@goakreo.com',
                'location' => 'Jl. Kandri No.157, Semarang',
                'desc' => 'Historic cave with surrounding reservoir.',
            ],
            [
                'name' => 'Kampung Pelangi Art',
                'phonenum' => '(024) 9999-1258',
                'email' => 'art@kampungpelangi.com',
                'location' => 'Jl. DR. Sutomo No.158, Semarang',
                'desc' => 'Colorful village with art installations.',
            ],
            [
                'name' => 'Museum Ronggowarsito Complex',
                'phonenum' => '(024) 1111-1259',
                'email' => 'complex@ronggowarsito.com',
                'location' => 'Jl. Abdulrahman Saleh No.159, Semarang',
                'desc' => 'Cultural museum with historic artifacts.',
            ],
            [
                'name' => 'Marina Beach Resort',
                'phonenum' => '(024) 2222-1260',
                'email' => 'resort@marina.com',
                'location' => 'Jl. Marina No.160, Semarang',
                'desc' => 'Beachfront recreation area with facilities.',
            ],
            [
                'name' => 'Tay Kak Sie Temple',
                'phonenum' => '(024) 3333-1261',
                'email' => 'temple@taykaksie.com',
                'location' => 'Jl. Gang Lombok No.161, Semarang',
                'desc' => 'Historic Chinese temple with cultural significance.',
             ],
             [
                'name' => 'Puri Maerokoco Park',
                'phonenum' => '(024) 4444-1262',
                'email' => 'park@purimaerokoco.com',
                'location' => 'Jl. Anjasmoro No.162, Semarang',
                'desc' => 'Cultural park with traditional architecture.',
             ],
             [
                'name' => 'Gereja Blenduk Heritage',
                'phonenum' => '(024) 5555-1263',
                'email' => 'heritage@gerejablenduk.com',
                'location' => 'Jl. Letjen Suprapto No.163, Semarang',
                'desc' => 'Historic Protestant church with Dutch architecture.',
             ],
             [
                'name' => 'Gedong Songo Complex',
                'phonenum' => '(024) 6666-1264',
                'email' => 'complex@gedongsongo.com',
                'location' => 'Jl. Bandungan No.164, Semarang',
                'desc' => 'Ancient Hindu temple complex on mountainside.',
             ],
             [
                'name' => 'Museum Mandala Bhakti',
                'phonenum' => '(024) 7777-1265',
                'email' => 'museum@mandalabhakti.com',
                'location' => 'Jl. Pemuda No.165, Semarang',
                'desc' => 'Military history museum with historic collections.',
             ],
             [
                'name' => 'Taman Budaya Center',
                'phonenum' => '(024) 8888-1266',
                'email' => 'center@tamanbudaya.com',
                'location' => 'Jl. Fatmawati No.166, Semarang',
                'desc' => 'Cultural park featuring traditional arts.',
             ],
             [
                'name' => 'Pagoda Avalokitesvara',
                'phonenum' => '(024) 9999-1267',
                'email' => 'pagoda@avalokitesvara.com',
                'location' => 'Jl. Pekojan No.167, Semarang',
                'desc' => 'Buddhist pagoda with religious significance.',
             ],
             [
                'name' => 'Taman Lele Park',
                'phonenum' => '(024) 1111-1268',
                'email' => 'park@tamanlele.com',
                'location' => 'Jl. Walisongo No.168, Semarang',
                'desc' => 'Family park with fishing and recreation areas.',
             ],
             [
                'name' => 'Railway Museum Complex',
                'phonenum' => '(024) 2222-1269',
                'email' => 'complex@railwaymuseum.com',
                'location' => 'Jl. Ambarawa No.169, Semarang',
                'desc' => 'Historic railway museum with vintage trains.',
             ],
             [
                'name' => 'Indonesia Kaya Park',
                'phonenum' => '(024) 3333-1270',
                'email' => 'park@indonesiakaya.com',
                'location' => 'Jl. Pemuda No.170, Semarang',
                'desc' => 'Cultural park showcasing Indonesian heritage.',
             ],
             [
                'name' => 'Vihara Buddhagaya Temple',
                'phonenum' => '(024) 4444-1271',
                'email' => 'temple@buddhagaya.com',
                'location' => 'Jl. Pedurungan No.171, Semarang',
                'desc' => 'Buddhist temple with meditation halls.',
             ],
             [
                'name' => 'Batik Culture Center',
                'phonenum' => '(024) 5555-1272',
                'email' => 'center@batikculture.com',
                'location' => 'Jl. Pandanaran No.172, Semarang',
                'desc' => 'Cultural center for batik art and workshops.',
             ],
             [
                'name' => 'Margasatwa Zoo Park',
                'phonenum' => '(024) 6666-1273',
                'email' => 'park@margasatwa.com',
                'location' => 'Jl. Setiabudi No.173, Semarang',
                'desc' => 'Zoo with various animal species and education programs.',
             ],
             [
                'name' => 'Old City Museum 3D',
                'phonenum' => '(024) 7777-1274',
                'email' => 'museum@oldcity3d.com',
                'location' => 'Jl. Letjen Suprapto No.174, Semarang',
                'desc' => 'Interactive museum with 3D historical exhibits.',
             ],
             [
                'name' => 'Bukit Cinta Viewpoint',
                'phonenum' => '(024) 8888-1275',
                'email' => 'view@bukitcinta.com',
                'location' => 'Jl. Rawa Pening No.175, Semarang',
                'desc' => 'Scenic viewpoint overlooking Rawa Pening lake.',
             ],
             [
                'name' => 'Jatibarang Dam',
                'phonenum' => '(024) 9999-1276',
                'email' => 'dam@jatibarang.com',
                'location' => 'Jl. Jatibarang No.176, Semarang',
                'desc' => 'Dam with scenic views and recreation areas.',
             ],
             [
                'name' => 'Taman Wilis Garden',
                'phonenum' => '(024) 1111-1277',
                'email' => 'garden@tamanwilis.com',
                'location' => 'Jl. Wilis No.177, Semarang',
                'desc' => 'Public garden with walking trails and facilities.',
             ],
             [
                'name' => 'Tinjomoyo Forest',
                'phonenum' => '(024) 2222-1278',
                'email' => 'forest@tinjomoyo.com',
                'location' => 'Jl. Tinjomoyo No.178, Semarang',
                'desc' => 'Forest park with hiking trails and wildlife.',
             ],
             [
                'name' => 'Kauman Great Mosque',
                'phonenum' => '(024) 3333-1279',
                'email' => 'mosque@kauman.com',
                'location' => 'Jl. Kauman No.179, Semarang',
                'desc' => 'Historic mosque with traditional architecture.',
             ],
             [
                'name' => 'Jamu Museum Complex',
                'phonenum' => '(024) 4444-1280',
                'email' => 'complex@jamumuseum.com',
                'location' => 'Jl. Jamu No.180, Semarang',
                'desc' => 'Museum dedicated to traditional herbal medicine.',
             ],
             [
                'name' => 'Gombel View Park',
                'phonenum' => '(024) 5555-1281',
                'email' => 'park@gombelview.com',
                'location' => 'Jl. Gombel No.181, Semarang',
                'desc' => 'Hillside park with panoramic city views.',
             ],
             [
                'name' => 'Semirang Waterfall',
                'phonenum' => '(024) 6666-1282',
                'email' => 'waterfall@semirang.com',
                'location' => 'Jl. Semirang No.182, Ungaran',
                'desc' => 'Natural waterfall with hiking trails.',
             ],
             [
                'name' => 'Benteng Pendem Heritage',
                'phonenum' => '(024) 7777-1283',
                'email' => 'heritage@bentengpendem.com',
                'location' => 'Jl. Benteng No.183, Semarang',
                'desc' => 'Historic Dutch fort with military history.',
             ],
             [
                'name' => 'Maron Beach Park',
                'phonenum' => '(024) 8888-1284',
                'email' => 'park@maronbeach.com',
                'location' => 'Jl. Maron No.184, Semarang',
                'desc' => 'Coastal park with beach activities.',
             ],
             [
                'name' => 'Pandanaran Heritage Park',
                'phonenum' => '(024) 9999-1285',
                'email' => 'heritage@pandanaran.com',
                'location' => 'Jl. Pandanaran No.185, Semarang',
                'desc' => 'Historic park with cultural monuments.',
             ],
             [
                'name' => 'Umbul Sidomukti Resort',
                'phonenum' => '(024) 1111-1286',
                'email' => 'resort@umbulsidomukti.com',
                'location' => 'Jl. Sidomukti No.186, Ungaran',
                'desc' => 'Mountain resort with natural springs.',
             ],
             [
                'name' => 'Tirto Agung Park',
                'phonenum' => '(024) 2222-1287',
                'email' => 'park@tirtoagung.com',
                'location' => 'Jl. Tirto Agung No.187, Semarang',
                'desc' => 'Public park with water features.',
             ],
             [
                'name' => 'Benowo Waterfall',
                'phonenum' => '(024) 3333-1288',
                'email' => 'waterfall@benowo.com',
                'location' => 'Jl. Benowo No.188, Ungaran',
                'desc' => 'Scenic waterfall with nature trails.',
             ],
             [
                'name' => 'Bustaman Heritage Village',
                'phonenum' => '(024) 4444-1289',
                'email' => 'village@bustaman.com',
                'location' => 'Jl. Bustaman No.189, Semarang',
                'desc' => 'Historic village with cultural preservation.',
             ],
             [
                'name' => 'Miniature Park Semarang',
                'phonenum' => '(024) 5555-1290',
                'email' => 'park@miniature.com',
                'location' => 'Jl. Miniatur No.190, Semarang',
                'desc' => 'Park featuring miniature landmarks.',
             ],
             [
                'name' => 'MURI Museum',
                'phonenum' => '(024) 6666-1291',
                'email' => 'museum@muri.com',
                'location' => 'Jl. MURI No.191, Semarang',
                'desc' => 'Museum of Indonesian records and achievements.',
             ],
             [
                'name' => 'Semirang Adventure Park',
                'phonenum' => '(024) 7777-1292',
                'email' => 'adventure@semirang.com',
                'location' => 'Jl. Semirang No.192, Ungaran',
                'desc' => 'Adventure park with outdoor activities.',
             ],
             [
                'name' => 'Unyil Park',
                'phonenum' => '(024) 8888-1293',
                'email' => 'park@unyil.com',
                'location' => 'Jl. Unyil No.193, Semarang',
                'desc' => 'Theme park based on local cartoon character.',
             ],
             [
                'name' => 'Maria Kerep Shrine',
                'phonenum' => '(024) 9999-1294',
                'email' => 'shrine@mariakerep.com',
                'location' => 'Jl. Kerep No.194, Ambarawa',
                'desc' => 'Religious pilgrimage site with gardens.',
             ],
             [
                'name' => 'Kampung Tematik Center',
                'phonenum' => '(024) 1111-1295',
                'email' => 'center@kampungtematik.com',
                'location' => 'Jl. Tematik No.195, Semarang',
                'desc' => 'Themed village with cultural attractions.',
             ],
             [
                'name' => 'Sri Gunting Park',
                'phonenum' => '(024) 2222-1296',
                'email' => 'park@srigunting.com',
                'location' => 'Jl. Sri Gunting No.196, Semarang',
                'desc' => 'Historic town square with colonial architecture.',
             ],
             [
                'name' => 'Nyonya Meneer Museum',
                'phonenum' => '(024) 3333-1297',
                'email' => 'museum@nyonyameneer.com',
                'location' => 'Jl. Meneer No.197, Semarang',
                'desc' => 'Museum dedicated to traditional medicine history.',
             ],
             [
                'name' => 'Ngesrep Eco Park',
                'phonenum' => '(024) 4444-1298',
                'email' => 'eco@ngesrep.com',
                'location' => 'Jl. Ngesrep No.198, Semarang',
                'desc' => 'Ecological park with nature education.',
             ],
             [
                'name' => 'Industrial Heritage Park',
                'phonenum' => '(024) 5555-1299',
                'email' => 'heritage@industrial.com',
                'location' => 'Jl. Industri No.199, Semarang',
                'desc' => 'Park showcasing industrial heritage.',
             ],
             [
                'name' => 'Soeharto Monument',
                'phonenum' => '(024) 6666-1300',
                'email' => 'monument@soeharto.com',
                'location' => 'Jl. Soeharto No.200, Semarang',
                'desc' => 'Historic monument with surrounding gardens.',
             ],
             [
                'name' => 'Paragon City Mall',
                'phonenum' => '(024) 7777-1301',
                'email' => 'info@paragoncity.com',
                'location' => 'Jl. Pemuda No.201, Semarang',
                'desc' => 'Premium shopping mall with international brands.',
             ],
             [
                'name' => 'Ciputra Mall',
                'phonenum' => '(024) 8888-1302',
                'email' => 'info@ciputramall.com',
                'location' => 'Jl. Simpang Lima No.202, Semarang',
                'desc' => 'Large shopping center with entertainment facilities.',
             ],
             [
                'name' => 'DP Mall Center',
                'phonenum' => '(024) 9999-1303',
                'email' => 'center@dpmall.com',
                'location' => 'Jl. Pemuda No.203, Semarang',
                'desc' => 'Modern mall with diverse retail options.',
             ],
             [
                'name' => 'Java Mall Complex',
                'phonenum' => '(024) 1111-1304',
                'email' => 'complex@javamall.com',
                'location' => 'Jl. MT Haryono No.204, Semarang',
                'desc' => 'Shopping complex with local and international stores.',
             ],
             [
                'name' => 'Transmart Mall',
                'phonenum' => '(024) 2222-1305',
                'email' => 'mall@transmart.com',
                'location' => 'Jl. Setiabudi No.205, Semarang',
                'desc' => 'Hypermarket and entertainment complex.',
             ],
             [
                'name' => 'Johar Trade Center',
                'phonenum' => '(024) 3333-1306',
                'email' => 'trade@johar.com',
                'location' => 'Jl. Johar No.206, Semarang',
                'desc' => 'Historic market with modern facilities.',
             ],
             [
                'name' => 'Central City Mall',
                'phonenum' => '(024) 4444-1307',
                'email' => 'mall@centralcity.com',
                'location' => 'Jl. Brigjend Sudiarto No.207, Semarang',
                'desc' => 'Urban shopping center with various amenities.',
             ],
             [
                'name' => 'Ada Shopping Center',
                'phonenum' => '(024) 5555-1308',
                'email' => 'center@ada.com',
                'location' => 'Jl. Siliwangi No.208, Semarang',
                'desc' => 'Department store with complete shopping facilities.',
             ],
             [
                'name' => 'Dargo Plaza Mall',
                'phonenum' => '(024) 6666-1309',
                'email' => 'mall@dargoplaza.com',
                'location' => 'Jl. Dargo No.209, Semarang',
                'desc' => 'Community shopping center with local products.',
             ],
             [
                'name' => 'Simpang Lima Square',
                'phonenum' => '(024) 7777-1310',
                'email' => 'square@simpanglima.com',
                'location' => 'Jl. Simpang Lima No.210, Semarang',
                'desc' => 'Central shopping district with various outlets.',
             ],
             [
                'name' => 'Sri Ratu Department Store',
                'phonenum' => '(024) 8888-1311',
                'email' => 'store@sriratu.com',
                'location' => 'Jl. Pemuda No.211, Semarang',
                'desc' => 'Classic department store with fashion focus.',
             ],
             [
                'name' => 'Mataram Mall',
                'phonenum' => '(024) 9999-1312',
                'email' => 'mall@mataram.com',
                'location' => 'Jl. MT Haryono No.212, Semarang',
                'desc' => 'Shopping center with diverse retail options.',
             ],
             [
                'name' => 'Giant Retail Center',
                'phonenum' => '(024) 1111-1313',
                'email' => 'retail@giant.com',
                'location' => 'Jl. Pedurungan No.213, Semarang',
                'desc' => 'Large retail center with supermarket.',
             ],
             [
                'name' => 'Gramedia Book Mall',
                'phonenum' => '(024) 2222-1314',
                'email' => 'mall@gramedia.com',
                'location' => 'Jl. Pandanaran No.214, Semarang',
                'desc' => 'Book store and stationery center.',
             ],
             [
                'name' => 'Bulu Market Center',
                'phonenum' => '(024) 3333-1315',
                'email' => 'center@bulumarket.com',
                'location' => 'Jl. Bulu No.215, Semarang',
                'desc' => 'Traditional market with modern facilities.',
             ],
             [
                'name' => 'Plaza Simpang 5',
                'phonenum' => '(024) 4444-1316',
                'email' => 'plaza@simpang5.com',
                'location' => 'Jl. Simpang Lima No.216, Semarang',
                'desc' => 'Modern plaza with entertainment options.',
             ],
             [
                'name' => 'Kanjengan Market',
                'phonenum' => '(024) 5555-1317',
                'email' => 'market@kanjengan.com',
                'location' => 'Jl. Kanjengan No.217, Semarang',
                'desc' => 'Historic market with traditional goods.',
             ],
             [
                'name' => 'Creative Gallery Mall',
                'phonenum' => '(024) 6666-1318',
                'email' => 'mall@creativegallery.com',
                'location' => 'Jl. Gajahmada No.218, Semarang',
                'desc' => 'Art and craft shopping center.',
             ],
             [
                'name' => 'Rita Shopping Center',
                'phonenum' => '(024) 7777-1319',
                'email' => 'center@rita.com',
                'location' => 'Jl. Siliwangi No.219, Semarang',
                'desc' => 'Family shopping center with various departments.',
             ],
             [
                'name' => 'Peterongan Market',
                'phonenum' => '(024) 8888-1320',
                'email' => 'market@peterongan.com',
                'location' => 'Jl. Peterongan No.220, Semarang',
                'desc' => 'Traditional market with local specialties.',
             ],
             [
                'name' => 'Ace Hardware Center',
                'phonenum' => '(024) 9999-1321',
                'email' => 'center@acehardware.com',
                'location' => 'Jl. Pemuda No.221, Semarang',
                'desc' => 'Home improvement and lifestyle store.',
             ],
             [
                'name' => 'Matahari Plaza',
                'phonenum' => '(024) 1111-1322',
                'email' => 'plaza@matahari.com',
                'location' => 'Jl. Pandanaran No.222, Semarang',
                'desc' => 'Fashion department store with multiple brands.',
             ],
             [
                'name' => 'Superindo Express',
                'phonenum' => '(024) 2222-1323',
                'email' => 'express@superindo.com',
                'location' => 'Jl. Majapahit No.223, Semarang',
                'desc' => 'Supermarket with fresh produce section.',
             ],
             [
                'name' => 'Indomaret Point Plus',
                'phonenum' => '(024) 3333-1324',
                'email' => 'plus@indomaret.com',
                'location' => 'Jl. Gajah Mada No.224, Semarang',
                'desc' => 'Convenience store with additional services.',
             ],
             [
                'name' => 'Karangayu Market Center',
                'phonenum' => '(024) 4444-1325',
                'email' => 'center@karangayu.com',
                'location' => 'Jl. Karangayu No.225, Semarang',
                'desc' => 'Modern market with traditional elements.',
             ],
             [
                'name' => 'Pemuda Shopping Mall',
                'phonenum' => '(024) 5555-1326',
                'email' => 'mall@pemuda.com',
                'location' => 'Jl. Pemuda No.226, Semarang',
                'desc' => 'Youth-oriented shopping center.',
             ],
             [
                'name' => 'Art Market Gallery',
                'phonenum' => '(024) 6666-1327',
                'email' => 'gallery@artmarket.com',
                'location' => 'Jl. Diponegoro No.227, Semarang',
                'desc' => 'Art and craft market with gallery space.',
             ],
             [
                'name' => 'Metro Plaza Center',
                'phonenum' => '(024) 7777-1328',
                'email' => 'center@metroplaza.com',
                'location' => 'Jl. Metro No.228, Semarang',
                'desc' => 'Urban shopping plaza with modern facilities.',
             ],
             [
                'name' => 'Lotte Shopping Center',
                'phonenum' => '(024) 8888-1329',
                'email' => 'center@lotte.com',
                'location' => 'Jl. Gajahmada No.229, Semarang',
                'desc' => 'Korean-style shopping mall with food court.',
             ],
             [
                'name' => 'Gang Baru Market',
                'phonenum' => '(024) 9999-1330',
                'email' => 'market@gangbaru.com',
                'location' => 'Jl. Gang Baru No.230, Semarang',
                'desc' => 'Traditional Chinese market area.',
             ],
             [
                'name' => 'Banyumanik Mall',
                'phonenum' => '(024) 1111-1331',
                'email' => 'mall@banyumanik.com',
                'location' => 'Jl. Banyumanik No.231, Semarang',
                'desc' => 'Suburban shopping mall with various stores.',
             ],
             [
                'name' => 'The Marketplace Center',
                'phonenum' => '(024) 2222-1332',
                'email' => 'center@marketplace.com',
                'location' => 'Jl. Setiabudi No.232, Semarang',
                'desc' => 'Modern market with international products.',
             ],
             [
                'name' => 'Uniqlo Store Center',
                'phonenum' => '(024) 3333-1333',
                'email' => 'center@uniqlo.com',
                'location' => 'Jl. Pemuda No.233, Semarang',
                'desc' => 'Japanese fashion retail store.',
             ],
             [
                'name' => 'Rejomulyo Trade Center',
                'phonenum' => '(024) 4444-1334',
                'email' => 'trade@rejomulyo.com',
                'location' => 'Jl. Rejomulyo No.234, Semarang',
                'desc' => 'Wholesale trade center for various goods.',
             ],
             [
                'name' => 'Electronic City Mall',
                'phonenum' => '(024) 5555-1335',
                'email' => 'mall@electroniccity.com',
                'location' => 'Jl. MT Haryono No.235, Semarang',
                'desc' => 'Electronics and gadget shopping center.',
             ],
             [
                'name' => 'H&M Fashion Center',
                'phonenum' => '(024) 6666-1336',
                'email' => 'center@hnm.com',
                'location' => 'Jl. Pandanaran No.236, Semarang',
                'desc' => 'International fashion retail store.',
             ],
             [
                'name' => 'Ngaliyan Plaza',
                'phonenum' => '(024) 7777-1337',
                'email' => 'plaza@ngaliyan.com',
                'location' => 'Jl. Ngaliyan No.237, Semarang',
                'desc' => 'Community shopping plaza with local stores.',
             ],
             [
                'name' => 'Sport Station Center',
                'phonenum' => '(024) 8888-1338',
                'email' => 'center@sportstation.com',
                'location' => 'Jl. Pemuda No.238, Semarang',
                'desc' => 'Sports equipment and apparel store.',
             ],
             [
                'name' => 'Pedurungan Market',
                'phonenum' => '(024) 9999-1339',
                'email' => 'market@pedurungan.com',
                'location' => 'Jl. Pedurungan No.239, Semarang',
                'desc' => 'Local market with daily necessities.',
             ],
             [
                'name' => 'Guardian Health Center',
                'phonenum' => '(024) 1111-1340',
                'email' => 'health@guardian.com',
                'location' => 'Jl. Gajah Mada No.240, Semarang',
                'desc' => 'Health and beauty retail store.',
             ],
             [
                'name' => 'Zara Fashion Mall',
                'phonenum' => '(024) 2222-1341',
                'email' => 'mall@zara.com',
                'location' => 'Jl. Pemuda No.241, Semarang',
                'desc' => 'International fashion brand store.',
             ],
             [
                'name' => 'Langgar Market Center',
                'phonenum' => '(024) 3333-1342',
                'email' => 'center@langgar.com',
                'location' => 'Jl. Langgar No.242, Semarang',
                'desc' => 'Traditional market with modern facilities.',
             ],
             [
                'name' => 'Centro Department Store',
                'phonenum' => '(024) 4444-1343',
                'email' => 'store@centro.com',
                'location' => 'Jl. Simpang Lima No.243, Semarang',
                'desc' => 'Fashion department store with multiple brands.',
             ],
             [
                'name' => 'Planet Ban Store',
                'phonenum' => '(024) 5555-1344',
                'email' => 'store@planetban.com',
                'location' => 'Jl. Majapahit No.244, Semarang',
                'desc' => 'Automotive parts and service center.',
             ],
             [
                'name' => 'Waru Shopping Center',
                'phonenum' => '(024) 6666-1345',
                'email' => 'center@waru.com',
                'location' => 'Jl. Waru No.245, Semarang',
                'desc' => 'Local shopping center with various shops.',
             ],
             [
                'name' => 'Courts Megastore',
                'phonenum' => '(024) 7777-1346',
                'email' => 'mega@courts.com',
                'location' => 'Jl. Siliwangi No.246, Semarang',
                'desc' => 'Furniture and electronics retail store.',
             ],
             [
                'name' => 'Tlogosari Plaza',
                'phonenum' => '(024) 8888-1347',
                'email' => 'plaza@tlogosari.com',
                'location' => 'Jl. Tlogosari No.247, Semarang',
                'desc' => 'Community shopping plaza with restaurants.',
             ],
             [
                'name' => 'Miniso Lifestyle',
                'phonenum' => '(024) 9999-1348',
                'email' => 'lifestyle@miniso.com',
                'location' => 'Jl. Pemuda No.248, Semarang',
                'desc' => 'Japanese-inspired lifestyle store.',
             ],
             [
                'name' => 'Sampangan Market',
                'phonenum' => '(024) 1111-1349',
                'email' => 'market@sampangan.com',
                'location' => 'Jl. Sampangan No.249, Semarang',
                'desc' => 'Traditional market with local products.',
             ],
             [
                'name' => 'Erafone Digital Center',
                'phonenum' => '(024) 2222-1350',
                'email' => 'digital@erafone.com',
                'location' => 'Jl. Pandanaran No.250, Semarang',
                'desc' => 'Mobile phone and gadget retail store.',
             ],
             
        ];

        DB::table('places')->insert($placesData);
    }
}